



#define SHEET_USER 					 0
#define SHEET_USER_LEVEL 					 SHEET_USER + 1
#define SHEET_SEED 					 SHEET_USER_LEVEL + 1
#define SHEET_POT 					 SHEET_SEED + 1
#define SHEET_PEST 					 SHEET_POT + 1
#define SHEET_STOCK 					 SHEET_PEST + 1
#define SHEET_STOCK_UPGRADE 					 SHEET_STOCK + 1
#define SHEET_MACHINE 					 SHEET_STOCK_UPGRADE + 1
#define SHEET_MACHINE_UNLOCK 					 SHEET_MACHINE + 1
#define SHEET_MACHINE_UNLOCK_PROD_SLOT 					 SHEET_MACHINE_UNLOCK + 1
#define SHEET_PRODUCT 					 SHEET_MACHINE_UNLOCK_PROD_SLOT + 1
#define SHEET_MATERIAL 					 SHEET_PRODUCT + 1
#define SHEET_FLOOR_UNLOCK 					 SHEET_MATERIAL + 1
#define SHEET_IBSHOP_ITEM 					 SHEET_FLOOR_UNLOCK + 1
#define SHEET_PRIVATE_SHOP 					 SHEET_IBSHOP_ITEM + 1
#define SHEET_ACHIEVEMENT 					 SHEET_PRIVATE_SHOP + 1
#define SHEET_DIAMOND_SKIP_TIME 					 SHEET_ACHIEVEMENT + 1
#define SHEET_ITEM_DROP 					 SHEET_DIAMOND_SKIP_TIME + 1
#define SHEET_GOLD_XP_COEFFICIENT 					 SHEET_ITEM_DROP + 1
#define SHEET_PAYMENT 					 SHEET_GOLD_XP_COEFFICIENT + 1
#define SHEET_DAILY_ORDER 					 SHEET_PAYMENT + 1
#define SHEET_TUTORIAL 					 SHEET_DAILY_ORDER + 1
#define SHEET_VERSION 					 SHEET_TUTORIAL + 1
#define SHEET_FRIEND_BUG 					 SHEET_VERSION + 1
#define SHEET_DECOR 					 SHEET_FRIEND_BUG + 1
#define SHEET_MACHINE_APPRAISAL 					 SHEET_DECOR + 1
#define SHEET_OWL_SLOT_UNLOCK 					 SHEET_MACHINE_APPRAISAL + 1
#define SHEET_GIFTS_INFO 					 SHEET_OWL_SLOT_UNLOCK + 1
#define SHEET_NOTIFY_TEXT 					 SHEET_GIFTS_INFO + 1
#define SHEET_DAILY_GIFT 					 SHEET_NOTIFY_TEXT + 1
#define SHEET_FIRST_PAY 					 SHEET_DAILY_GIFT + 1
#define SHEET_CONSTANT 					 SHEET_FIRST_PAY + 1
#define SHEET_EVENT 					 SHEET_CONSTANT + 1
#define SHEET_EVENT_MAIN_OBJECT 					 SHEET_EVENT + 1
#define SHEET_EVENT_MAIN_ITEM 					 SHEET_EVENT_MAIN_OBJECT + 1
#define SHEET_GIFT_ALPHA_TEST 					 SHEET_EVENT_MAIN_ITEM + 1
#define SHEET_NPC_MERCHANT 					 SHEET_GIFT_ALPHA_TEST + 1
#define SHEET_FEED_INFO 					 SHEET_NPC_MERCHANT + 1
#define SHEET_CDN 					 SHEET_FEED_INFO + 1
#define SHEET_PAYMENT_EVENT 					 SHEET_CDN + 1
#define SHEET_EVENT_GLOBAL 					 SHEET_PAYMENT_EVENT + 1
#define SHEET_AIRSHIP 					 SHEET_EVENT_GLOBAL + 1
#define SHEET_ITEMS_VALUES 					 SHEET_AIRSHIP + 1
#define SHEET_TOM_KID 					 SHEET_ITEMS_VALUES + 1
#define SHEET_ROTA_FORTUNAE 					 SHEET_TOM_KID + 1
#define SHEET_ROTA_FORTUNAE_ITEMS 					 SHEET_ROTA_FORTUNAE + 1
#define SHEET_INVITE_FRIEND 					 SHEET_ROTA_FORTUNAE_ITEMS + 1
#define SHEET_EVENT_MID_AUTUMN 					 SHEET_INVITE_FRIEND + 1
#define SHEET_ORDER_EVENT 					 SHEET_EVENT_MID_AUTUMN + 1
#define SHEET_OPEN_EVENT_ITEM 					 SHEET_ORDER_EVENT + 1
#define SHEET_COMBO 					 SHEET_OPEN_EVENT_ITEM + 1
#define SHEET_DROP_CUSTOM 					 SHEET_COMBO + 1
#define SHEET_CLOSE_FRIEND 					 SHEET_DROP_CUSTOM + 1
#define SHEET_TREASURE_TRUNK 					 SHEET_CLOSE_FRIEND + 1
#define SHEET_GEO_IP 					 SHEET_TREASURE_TRUNK + 1
#define SHEET_MAX 					 SHEET_GEO_IP + 1


#define USER_GOLD 					 0
#define USER_DIAMOND 					 USER_GOLD + 1
#define USER_REPUTAION 					 USER_DIAMOND + 1
#define USER_FLOOR 					 USER_REPUTAION + 1
#define USER_PROPERTY_MAX 					 USER_FLOOR + 1


#define USER_LEVEL 					 0
#define USER_EXP_LVL 					 USER_LEVEL + 1
#define USER_SEED_ID_UNLOCK 					 USER_EXP_LVL + 1
#define USER_POT_ID_UNLOCK 					 USER_SEED_ID_UNLOCK + 1
#define USER_PROD_ID_UNLOCK 					 USER_POT_ID_UNLOCK + 1
#define USER_FLOOR_UNLOCK 					 USER_PROD_ID_UNLOCK + 1
#define USER_MACHINE_UNLOCK 					 USER_FLOOR_UNLOCK + 1
#define USER_ORDER_SLOT_UNLOCK 					 USER_MACHINE_UNLOCK + 1
#define USER_REWARD_GOLD 					 USER_ORDER_SLOT_UNLOCK + 1
#define USER_REWARD_REPUTATION 					 USER_REWARD_GOLD + 1
#define USER_REWARD_DIAMOND 					 USER_REWARD_REPUTATION + 1
#define USER_REWARD_ITEM 					 USER_REWARD_DIAMOND + 1
#define USER_LEVEL_SHARE_REWARD 					 USER_REWARD_ITEM + 1
#define USER_NEW_COMER_GIFT 					 USER_LEVEL_SHARE_REWARD + 1
#define USER_UNLOCK_PROPERTY_MAX 					 USER_NEW_COMER_GIFT + 1


#define SEED_ID 					 0
#define SEED_NAME 					 SEED_ID + 1
#define SEED_GROW_TIME 					 SEED_NAME + 1
#define SEED_HARVEST_EXP 					 SEED_GROW_TIME + 1
#define SEED_ITEM_RECEIVE_RATIO 					 SEED_HARVEST_EXP + 1
#define SEED_DIAMOND_SKIP_TIME 					 SEED_ITEM_RECEIVE_RATIO + 1
#define SEED_DIAMOND_BUY 					 SEED_DIAMOND_SKIP_TIME + 1
#define SEED_GOLD_BASIC 					 SEED_DIAMOND_BUY + 1
#define SEED_EXP_BASIC 					 SEED_GOLD_BASIC + 1
#define SEED_GOLD_SELL_DEFAULT 					 SEED_EXP_BASIC + 1
#define SEED_GOLD_SELL_MIN 					 SEED_GOLD_SELL_DEFAULT + 1
#define SEED_GOLD_SELL_MAX 					 SEED_GOLD_SELL_MIN + 1
#define SEED_BUG_ID 					 SEED_GOLD_SELL_MAX + 1
#define SEED_BUG_APPEAR_RATIO 					 SEED_BUG_ID + 1
#define SEED_LEVEL_UNLOCK 					 SEED_BUG_APPEAR_RATIO + 1
#define SEED_SEED_TIME 					 SEED_LEVEL_UNLOCK + 1
#define SEED_GOLD_BASIC_DO 					 SEED_SEED_TIME + 1
#define SEED_EXP_BASIC_DO_FREE 					 SEED_GOLD_BASIC_DO + 1
#define SEED_EXP_BASIC_DO_PAID 					 SEED_EXP_BASIC_DO_FREE + 1
#define SEED_NPC_BUY_PRICE 					 SEED_EXP_BASIC_DO_PAID + 1

#define SEED_NAME_EN 					 SEED_NPC_BUY_PRICE + 1
#define SEED_NAME_SC 					 SEED_NAME_EN + 1
#define SEED_NAME_TC 					 SEED_NAME_SC + 1
#define SEED_PROPERTY_MAX 					 SEED_NAME_TC + 1


#define POT_ID 					 0
#define POT_NAME 					 POT_ID + 1
#define POT_EXP_INCREASE 					 POT_NAME + 1
#define POT_TIME_DECREASE 					 POT_EXP_INCREASE + 1
#define POT_GOLD_UPGRADE 					 POT_TIME_DECREASE + 1
#define POT_UPGRADE_REQUIREMENT 					 POT_GOLD_UPGRADE + 1
#define POT_UPGRADE_RATIO 					 POT_UPGRADE_REQUIREMENT + 1
#define POT_GOLD_DEFAULT 					 POT_UPGRADE_RATIO + 1
#define POT_GOLD_MIN 					 POT_GOLD_DEFAULT + 1
#define POT_GOLD_MAX 					 POT_GOLD_MIN + 1
#define POT_BUG_APPEAR_RATIO 					 POT_GOLD_MAX + 1
#define POT_LEVEL_UNLOCK 					 POT_BUG_APPEAR_RATIO + 1
#define POT_BLESSING_RATIO 					 POT_LEVEL_UNLOCK + 1
#define POT_BAD_LUCK_RATIO 					 POT_BLESSING_RATIO + 1
#define POT_COMBO_EXP_BONUS 					 POT_BAD_LUCK_RATIO + 1
#define POT_COMBO_TIME_BONUS 					 POT_COMBO_EXP_BONUS + 1
#define POT_COMBO_BUG_BONUS 					 POT_COMBO_TIME_BONUS + 1
#define POT_ORDER_EXP_BONUS_PLANT 					 POT_COMBO_BUG_BONUS + 1
#define POT_ORDER_EXP_BONUS_BUG 					 POT_ORDER_EXP_BONUS_PLANT + 1
#define POT_APPRAISAL 					 POT_ORDER_EXP_BONUS_BUG + 1
#define POT_ORDER_GOLD_BONUS 					 POT_APPRAISAL + 1
#define POT_ORDER_XP_BONUS 					 POT_ORDER_GOLD_BONUS + 1

#define POT_NAME_EN 					 POT_ORDER_XP_BONUS + 1
#define POT_NAME_SC 					 POT_NAME_EN + 1
#define POT_NAME_TC 					 POT_NAME_SC + 1
#define POT_UPGRADABLE 					 POT_NAME_TC + 1
#define POT_PROPERTY_MAX 					 POT_UPGRADABLE + 1


#define PEST_ID 					 0
#define PEST_NAME 					 PEST_ID + 1
#define PEST_DIAMOND_BUY 					 PEST_NAME + 1
#define PEST_GOLD_BASIC 					 PEST_DIAMOND_BUY + 1
#define PEST_EXP_BASIC 					 PEST_GOLD_BASIC + 1
#define PEST_GOLD_DEFAULT 					 PEST_EXP_BASIC + 1
#define PEST_GOLD_MIN 					 PEST_GOLD_DEFAULT + 1
#define PEST_GOLD_MAX 					 PEST_GOLD_MIN + 1
#define PEST_NPC_BUY_PRICE 					 PEST_GOLD_MAX + 1

#define PEST_NAME_EN 					 PEST_NPC_BUY_PRICE + 1
#define PEST_NAME_SC 					 PEST_NAME_EN + 1
#define PEST_NAME_TC 					 PEST_NAME_SC + 1
#define PEST_PROPERTY_MAX 					 PEST_NAME_TC + 1


#define STOCK_ID 					 0
#define STOCK_NAME 					 STOCK_ID + 1
#define STOCK_CAPACITY_MAX 					 STOCK_NAME + 1
#define STOCK_CAPACITY_ADD 					 STOCK_CAPACITY_MAX + 1
#define STOCK_CAPACITY_PLUS 					 STOCK_CAPACITY_ADD + 1
#define STOCK_VIP_PLUS 					 STOCK_CAPACITY_PLUS + 1

#define STOCK_NAME_EN 					 STOCK_VIP_PLUS + 1
#define STOCK_NAME_SC 					 STOCK_NAME_EN + 1
#define STOCK_NAME_TC 					 STOCK_NAME_SC + 1
#define STOCK_PROPERTY_MAX 					 STOCK_NAME_TC + 1


#define STOCK_1 					 0
#define STOCK_2 					 STOCK_1 + 1
#define STOCK_3 					 STOCK_2 + 1
#define STOCK_APPRAISAL 					 STOCK_3 + 1
#define STOCK_UPGRADE_PROPERTY_MAX 					 STOCK_APPRAISAL + 1


#define MACHINE_FLOOR 					 0
#define MACHINE_ID 					 MACHINE_FLOOR + 1
#define MACHINE_NAME 					 MACHINE_ID + 1
#define MACHINE_LEVEL_UNLOCK 					 MACHINE_NAME + 1
#define MACHINE_GOLD_START 					 MACHINE_LEVEL_UNLOCK + 1
#define MACHINE_TIME_START 					 MACHINE_GOLD_START + 1
#define MACHINE_PRODUCT_ID 					 MACHINE_TIME_START + 1
#define MACHINE_DURABILITY 					 MACHINE_PRODUCT_ID + 1

#define MACHINE_NAME_EN 					 MACHINE_DURABILITY + 1
#define MACHINE_NAME_SC 					 MACHINE_NAME_EN + 1
#define MACHINE_NAME_TC 					 MACHINE_NAME_SC + 1
#define MACHINE_PROPERTY_MAX 					 MACHINE_NAME_TC + 1


#define MACHINE_LEVEL1 					 0
#define MACHINE_LEVEL2 					 MACHINE_LEVEL1 + 1
#define MACHINE_LEVEL3 					 MACHINE_LEVEL2 + 1
#define MACHINE_LEVEL4 					 MACHINE_LEVEL3 + 1
#define MACHINE_LEVEL5 					 MACHINE_LEVEL4 + 1
#define MACHINE_LEVEL6 					 MACHINE_LEVEL5 + 1
#define MACHINE_LEVEL7 					 MACHINE_LEVEL6 + 1
#define MACHINE_LEVEL8 					 MACHINE_LEVEL7 + 1
#define MACHINE_LEVEL_MAX 					 MACHINE_LEVEL8 + 1

#define MACHINE_ACTIVE_TIME 					 0
#define MACHINE_GOLD_UNLOCK 					 MACHINE_ACTIVE_TIME + 1
#define MACHINE_UPGRADE_RATIO 					 MACHINE_GOLD_UNLOCK + 1
#define MACHINE_EXP_BONUS 					 MACHINE_UPGRADE_RATIO + 1
#define MACHINE_REDUCE_TIME 					 MACHINE_EXP_BONUS + 1
#define MACHINE_EXP_ORDER 					 MACHINE_REDUCE_TIME + 1
#define MACHINE_GOLD_ORDER 					 MACHINE_EXP_ORDER + 1
#define MACHINE_GOLD_MAINTAIN 					 MACHINE_GOLD_ORDER + 1
#define MACHINE_UNLOCK_PROPERTY_MAX 					 MACHINE_GOLD_MAINTAIN + 1


#define MACHINE_SLOT_0 					 0
#define MACHINE_SLOT_1 					 MACHINE_SLOT_0 + 1
#define MACHINE_SLOT_2 					 MACHINE_SLOT_1 + 1
#define MACHINE_SLOT_3 					 MACHINE_SLOT_2 + 1
#define MACHINE_SLOT_4 					 MACHINE_SLOT_3 + 1
#define MACHINE_SLOT_5 					 MACHINE_SLOT_4 + 1
#define MACHINE_SLOT_6 					 MACHINE_SLOT_5 + 1
#define MACHINE_SLOT_7 					 MACHINE_SLOT_6 + 1
#define MACHINE_SLOT_8 					 MACHINE_SLOT_7 + 1
#define MACHINE_SLOT_PROPERTY_MAX 					 MACHINE_SLOT_8 + 1


#define PRODUCT_ID 					 0
#define PRODUCT_NAME 					 PRODUCT_ID + 1
#define PRODUCT_LEVEL_UNLOCK 					 PRODUCT_NAME + 1
#define PRODUCT_MACHINE_ID 					 PRODUCT_LEVEL_UNLOCK + 1
#define PRODUCT_ITEMS_TYPE_ID_NUM 					 PRODUCT_MACHINE_ID + 1
#define PRODUCT_PRODUCTION_TIME 					 PRODUCT_ITEMS_TYPE_ID_NUM + 1
#define PRODUCT_EXP_RECEIVE 					 PRODUCT_PRODUCTION_TIME + 1
#define PRODUCT_DIAMOND_BUY 					 PRODUCT_EXP_RECEIVE + 1
#define PRODUCT_GOLD_BASIC 					 PRODUCT_DIAMOND_BUY + 1
#define PRODUCT_EXP_BASIC 					 PRODUCT_GOLD_BASIC + 1
#define PRODUCT_GOLD_DEFAULT 					 PRODUCT_EXP_BASIC + 1
#define PRODUCT_GOLD_MIN 					 PRODUCT_GOLD_DEFAULT + 1
#define PRODUCT_GOLD_MAX 					 PRODUCT_GOLD_MIN + 1
#define PRODUCT_NPC_BUY_PRICE 					 PRODUCT_GOLD_MAX + 1

#define PRODUCT_NAME_EN 					 PRODUCT_NPC_BUY_PRICE + 1
#define PRODUCT_NAME_SC 					 PRODUCT_NAME_EN + 1
#define PRODUCT_NAME_TC 					 PRODUCT_NAME_SC + 1
#define PRODUCT_PROPERTY_MAX 					 PRODUCT_NAME_TC + 1


#define MATERIAL_ID 					 0
#define MATERIAL_NAME 					 MATERIAL_ID + 1
#define MATERIAL_DIAMOND_BUY 					 MATERIAL_NAME + 1
#define MATERIAL_GOLD_DEFAULT 					 MATERIAL_DIAMOND_BUY + 1
#define MATERIAL_GOLD_MIN 					 MATERIAL_GOLD_DEFAULT + 1
#define MATERIAL_GOLD_MAX 					 MATERIAL_GOLD_MIN + 1
#define MATERIAL_4_LEAF_LUCKY_PERCENT 					 MATERIAL_GOLD_MAX + 1
#define MATERIAL_FERTILIZER_TIME_REDUCE 					 MATERIAL_4_LEAF_LUCKY_PERCENT + 1

#define MATERIAL_NAME_EN 					 MATERIAL_FERTILIZER_TIME_REDUCE + 1
#define MATERIAL_NAME_SC 					 MATERIAL_NAME_EN + 1
#define MATERIAL_NAME_TC 					 MATERIAL_NAME_SC + 1
#define MATERIAL_PROPERTY_MAX 					 MATERIAL_NAME_TC + 1


#define FLOOR_UNLOCK_ID 					 0
#define FLOOR_UNLOCK_USER_LEVEL 					 FLOOR_UNLOCK_ID + 1
#define FLOOR_UNLOCK_GOLD 					 FLOOR_UNLOCK_USER_LEVEL + 1
#define FLOOR_UNLOCK_REPUTATION 					 FLOOR_UNLOCK_GOLD + 1
#define FLOOR_UNLOCK_MATERIAL_ID_NUM 					 FLOOR_UNLOCK_REPUTATION + 1
#define FLOOR_APPRAISAL 					 FLOOR_UNLOCK_MATERIAL_ID_NUM + 1
#define FLOOR_UNLOCK_PROPERTY_MAX 					 FLOOR_APPRAISAL + 1


#define IBSHOP_ID 					 0
#define IBSHOP_NAME 					 IBSHOP_ID + 1
#define IBSHOP_DESCRIPTION 					 IBSHOP_NAME + 1
#define IBSHOP_TYPE 					 IBSHOP_DESCRIPTION + 1
#define IBSHOP_ITEM_NAME 					 IBSHOP_TYPE + 1
#define IBSHOP_ITEM_QUANTITY 					 IBSHOP_ITEM_NAME + 1
#define IBSHOP_IS_ACTIVE 					 IBSHOP_ITEM_QUANTITY + 1
#define IBSHOP_IS_NEW 					 IBSHOP_IS_ACTIVE + 1
#define IBSHOP_IS_HOT 					 IBSHOP_IS_NEW + 1
#define IBSHOP_IS_SALE_OFF 					 IBSHOP_IS_HOT + 1
#define IBSHOP_SALE_OFF_PERCENT 					 IBSHOP_IS_SALE_OFF + 1
#define IBSHOP_HAS_PROMOTION 					 IBSHOP_SALE_OFF_PERCENT + 1
#define IBSHOP_GIFT_WHEN_BUY 					 IBSHOP_HAS_PROMOTION + 1
#define IBSHOP_REQUIRED_GOLD 					 IBSHOP_GIFT_WHEN_BUY + 1
#define IBSHOP_REQUIRED_DIAMOND 					 IBSHOP_REQUIRED_GOLD + 1
#define IBSHOP_REQUIRED_REPUTATION 					 IBSHOP_REQUIRED_DIAMOND + 1
#define IBSHOP_HAS_TIME_LIMIT 					 IBSHOP_REQUIRED_REPUTATION + 1
#define IBSHOP_SALE_DURATION 					 IBSHOP_HAS_TIME_LIMIT + 1
#define IBSHOP_HAS_SALE_LIMIT 					 IBSHOP_SALE_DURATION + 1
#define IBSHOP_SALE_TOTAL_QUANTITY 					 IBSHOP_HAS_SALE_LIMIT + 1
#define IBSHOP_UNLOCK_LEVEL 					 IBSHOP_SALE_TOTAL_QUANTITY + 1
#define IBSHOP_DISPLAY_INDEX 					 IBSHOP_UNLOCK_LEVEL + 1
#define IBSHOP_EVENT_GIFT 					 IBSHOP_DISPLAY_INDEX + 1
#define IBSHOP_NAME_EN 					 IBSHOP_EVENT_GIFT + 1
#define IBSHOP_DESCRIPTION_EN 					 IBSHOP_NAME_EN + 1
#define IBSHOP_NAME_SC 					 IBSHOP_DESCRIPTION_EN + 1
#define IBSHOP_DESCRIPTION_SC 					 IBSHOP_NAME_SC + 1
#define IBSHOP_NAME_TC 					 IBSHOP_DESCRIPTION_SC + 1
#define IBSHOP_DESCRIPTION_TC 					 IBSHOP_NAME_TC + 1
#define IBSHOP_PROPERTY_MAX 					 IBSHOP_DESCRIPTION_TC + 1



#define IBS_TAB_DIAMOND 					 0
#define IBS_TAB_GOLD 					 1
#define IBS_TAB_POT 					 2
#define IBS_TAB_DECOR 					 3
#define IBS_TAB_UPGRADE 					 4
#define IBS_TAB_MACHINE 					 5
#define IBS_TAB_MISCELLANEOUS 					 6
#define IBS_TAB_PLANT 					 7
#define IBS_TAB_OWL_FOOD 					 8
#define IBS_TAB_MAX 					 9


#define PS_SHOP_SLOT_ID 					 0
#define PS_SHOP_REQUIRED_FRIEND 					 PS_SHOP_SLOT_ID + 1
#define PS_SHOP_REQUIRED_DIAMOND 					 PS_SHOP_REQUIRED_FRIEND + 1
#define PS_SHOP_REQUIRED_DIAMOND_CANCEL 					 PS_SHOP_REQUIRED_DIAMOND + 1
#define PS_SHOP_PROPERTY_MAX 					 PS_SHOP_REQUIRED_DIAMOND_CANCEL + 1


#define ACHIEVEMENT_INDEX 					 0
#define ACHIEVEMENT_COMMAND_ID 					 1
#define ACHIEVEMENT_EXTRA_COMMAND_INFO 					 2
#define ACHIEVEMENT_DESCRIPTION 					 3
#define ACHIEVEMENT_TARGET_1 					 4
#define ACHIEVEMENT_TARGET_2 					 5
#define ACHIEVEMENT_TARGET_3 					 6
#define ACHIEVEMENT_GIFT_1 					 7
#define ACHIEVEMENT_GIFT_2 					 8
#define ACHIEVEMENT_GIFT_3 					 9
#define ACHIEVEMENT_GIFT_SPECIAL 					 10
#define ACHIEVEMENT_NAME 					 11
#define ACHIEVEMENT_NAME_EN 					 12
#define ACHIEVEMENT_DESCRIPTION_EN 					 13
#define ACHIEVEMENT_PROPERTY_MAX 					 14

#define ACHIEVEMENT_GIFT_INDEX_1 					 1
#define ACHIEVEMENT_GIFT_INDEX_2 					 2
#define ACHIEVEMENT_GIFT_INDEX_3 					 3


#define DIAMOND_SKIP_TIME_PLANT_TIME_RANGE 					 0
#define DIAMOND_SKIP_TIME_PLANT_RATIO 					 DIAMOND_SKIP_TIME_PLANT_TIME_RANGE + 1
#define DIAMOND_SKIP_TIME_PLANT_DIAMOND_DEFAULT 					 DIAMOND_SKIP_TIME_PLANT_RATIO + 1
#define DIAMOND_SKIP_TIME_PRODUCT_TIME_RANGE 					 DIAMOND_SKIP_TIME_PLANT_DIAMOND_DEFAULT + 1
#define DIAMOND_SKIP_TIME_PRODUCT_RATIO 					 DIAMOND_SKIP_TIME_PRODUCT_TIME_RANGE + 1
#define DIAMOND_SKIP_TIME_PRODUCT_DIAMOND_DEFAULT 					 DIAMOND_SKIP_TIME_PRODUCT_RATIO + 1
#define DIAMOND_SKIP_TIME_MACHINE_TIME_RANGE 					 DIAMOND_SKIP_TIME_PRODUCT_DIAMOND_DEFAULT + 1
#define DIAMOND_SKIP_TIME_MACHINE_RATIO 					 DIAMOND_SKIP_TIME_MACHINE_TIME_RANGE + 1
#define DIAMOND_SKIP_TIME_MACHINE_DIAMOND_DEFAULT 					 DIAMOND_SKIP_TIME_MACHINE_RATIO + 1
#define DIAMOND_SKIP_TIME_PROPERTY_MAX 					 DIAMOND_SKIP_TIME_MACHINE_DIAMOND_DEFAULT + 1

#define DIAMOND_SKIP_TIME_PLANT 					 0
#define DIAMOND_SKIP_TIME_PRODUCT 					 DIAMOND_SKIP_TIME_PLANT + 1
#define DIAMOND_SKIP_TIME_MACHINE 					 DIAMOND_SKIP_TIME_PRODUCT + 1


#define DROP_INDEX 					 0
#define DROP_LEVEL 					 0
#define DROP_ITEM_GACH 					 1
#define DROP_ITEM_SONDO 					 2
#define DROP_ITEM_GO 					 3
#define DROP_ITEM_DA 					 4
#define DROP_ITEM_SONVANG 					 5
#define DROP_ITEM_DINH 					 6
#define DROP_ITEM_NGOI 					 7
#define DROP_ITEM_SONDEN 					 8
#define DROP_ITEM_SAT 					 9
#define DROP_ITEM_VOT 					 10
#define DROP_ITEM_NUOCTHAN 					 11
#define DROP_ITEM_KEODANMAY 					 12
#define DROP_ITEM_VOTDAI 					 13
#define DROP_ITEM_BANH_TRUNG_THU 					 14
#define DROP_ITEM_EVENT_1 					 15
#define DROP_ITEM_EVENT_2 					 16
#define DROP_ITEM_EVENT_3 					 17
#define DROP_ITEM_TREASURE 					 18
#define DROP_ITEM_PROPERTY_MAX 					 DROP_ITEM_TREASURE + 1


#define GOLD_XP_COEFFICIENT_RATE 					 0
#define GOLD_XP_COEFFICIENT_RATE_RANGE 					 GOLD_XP_COEFFICIENT_RATE + 1
#define GOLD_XP_COEFFICIENT_MIN 					 GOLD_XP_COEFFICIENT_RATE_RANGE + 1
#define GOLD_XP_COEFFICIENT_MAX 					 GOLD_XP_COEFFICIENT_MIN + 1
#define GOLD_XP_COEFFICIENT_PROPERTY_MAX 					 GOLD_XP_COEFFICIENT_MAX + 1


#define PAYMENT_PACK_ID 					 0
#define PAYMENT_PACK_NAME 					 1
#define PAYMENT_PACK_DESCRIPTION 					 2
#define PAYMENT_TYPE 					 3
#define PAYMENT_OPERATOR 					 4
#define PAYMENT_GROSS_AMOUNT 					 5
#define PAYMENT_SMS_STRUCTURE 					 6
#define PAYMENT_SMS_ADDRESS 					 7
#define PAYMENT_IS_ACTIVE 					 8
#define PAYMENT_IS_NEW 					 9
#define PAYMENT_IS_HOT 					 10
#define PAYMENT_HAS_PROMOTION 					 11
#define PAYMENT_PROMOTION_PERCENT 					 12
#define PAYMENT_DIAMOND_RECEIVE_REAL 					 13
#define PAYMENT_DIAMOND_RECEIVE_BONUS 					 14
#define PAYMENT_DIAMOND_RECEIVE_REAL_DISPLAY 					 15
#define PAYMENT_DIAMOND_RECEIVE_BONUS_DISPLAY 					 16
#define PAYMENT_DIAMOND_RECEIVE_BONUS_FIRST_PAY 					 17

#define PAYMENT_PACK_NAME_EN 					 18
#define PAYMENT_PACK_DESCRIPTION_EN 					 19
#define PAYMENT_PACK_NAME_SC 					 20
#define PAYMENT_PACK_DESCRIPTION_SC 					 21
#define PAYMENT_PACK_NAME_TC 					 22
#define PAYMENT_PACK_DESCRIPTION_TC 					 23
#define PAYMENT_PACK_ANDROID_PRODUCT_ID 					 24
#define PAYMENT_PACK_APPLE_PRODUCT_ID 					 25
#define PAYMENT_PACK_WIN_PRODUCT_ID 					 26
#define PAYMENT_PROPERTY_MAX 					 27

#define PAYMENT_CARD_ZING 					 0
#define PAYMENT_CARD_VNP 					 1
#define PAYMENT_CARD_VMS 					 2
#define PAYMENT_CARD_VTT 					 3


#define DAILY_ORDER_INDEX 					 0
#define DAILY_ORDER_GOLD_PER_DIAMOND 					 DAILY_ORDER_INDEX + 1
#define DAILY_ORDER_PROPERTY_MAX 					 DAILY_ORDER_GOLD_PER_DIAMOND + 1


#define TUTORIAL_ID 					 0
#define TUTORIAL_EXP 					 TUTORIAL_ID + 1

#define TUTORIAL_SLIDE_TO_FIRST_FLOOR 					 0
#define TUTORIAL_HARVEST 					 TUTORIAL_SLIDE_TO_FIRST_FLOOR + 1
#define TUTORIAL_AFTER_HARVEST 					 TUTORIAL_HARVEST + 1
#define TUTORIAL_PLANT 					 TUTORIAL_AFTER_HARVEST + 1
#define TUTORIAL_AFTER_PLANT 					 TUTORIAL_PLANT + 1
#define TUTORIAL_RECEIVE_PLANT_REWARD 					 TUTORIAL_AFTER_PLANT + 1
#define TUTORIAL_CATCH_BUG 					 TUTORIAL_RECEIVE_PLANT_REWARD + 1
#define TUTORIAL_AFTER_CATCH_BUG 					 TUTORIAL_CATCH_BUG + 1
#define TUTORIAL_OPEN_MACHINE 					 TUTORIAL_AFTER_CATCH_BUG + 1
#define TUTORIAL_SKIP_TIME_FREEZE_MACHINE 					 TUTORIAL_OPEN_MACHINE + 1
#define TUTORIAL_PRODUCT 					 TUTORIAL_SKIP_TIME_FREEZE_MACHINE + 1
#define TUTORIAL_SKIP_TIME 					 TUTORIAL_PRODUCT + 1
#define TUTORIAL_AFTER_SKIP_TIME 					 TUTORIAL_SKIP_TIME + 1
#define TUTORIAL_RECEIVE_ORDER 					 TUTORIAL_AFTER_SKIP_TIME + 1
#define TUTORIAL_DELIVERY_ORDER 					 TUTORIAL_RECEIVE_ORDER + 1
#define TUTORIAL_RECEIVE_ORDER_REWARD 					 TUTORIAL_DELIVERY_ORDER + 1
#define TUTORIAL_AFTER_RECEIVE_ORDER_REWARD 					 TUTORIAL_RECEIVE_ORDER_REWARD + 1
#define TUTORIAL_OPEN_NEW_FLOOR 					 TUTORIAL_AFTER_RECEIVE_ORDER_REWARD + 1
#define TUTORIAL_NPC_MACHINE_REPAIR 					 TUTORIAL_OPEN_NEW_FLOOR + 1
#define TUTORIAL_AFTER_NPC_MACHINE_REPAIR 					 TUTORIAL_NPC_MACHINE_REPAIR + 1
#define TUTORIAL_PUT_POT 					 TUTORIAL_AFTER_NPC_MACHINE_REPAIR + 1
#define TUTORIAL_BUY_POT 					 TUTORIAL_PUT_POT + 1
#define TUTORIAL_MOVE_POT 					 TUTORIAL_BUY_POT + 1
#define TUTORIAL_PRIVATE_SHOP_GUIDE 					 TUTORIAL_MOVE_POT + 1
#define TUTORIAL_BUY_ITEM_PRIVATE_SHOP 					 TUTORIAL_PRIVATE_SHOP_GUIDE + 1
#define TUTORIAL_NEWSBOARD 					 TUTORIAL_BUY_ITEM_PRIVATE_SHOP + 1
#define TUTORIAL_CONNECT_SNS 					 TUTORIAL_NEWSBOARD + 1
#define TUTORIAL_UPGRADE_POT 					 TUTORIAL_CONNECT_SNS + 1
#define TUTORIAL_MAX 					 TUTORIAL_UPGRADE_POT + 1


#define VERSION_ID 					 0
#define VERSION_PLATFORM 					 VERSION_ID + 1
#define VERSION_RESOLUTION 					 VERSION_PLATFORM + 1
#define VERSION_DISTRIBUTOR 					 VERSION_RESOLUTION + 1
#define VERSION_NUMBER 					 VERSION_DISTRIBUTOR + 1
#define VERSION_LINK 					 VERSION_NUMBER + 1
#define VERSION_FORCE_UPDATE 					 VERSION_LINK + 1
#define VERSION_MAX 					 VERSION_FORCE_UPDATE + 1

#define VERSION_WRONG_UPDATE 					 0
#define VERSION_HAS_NOT_UPDATE 					 VERSION_WRONG_UPDATE + 1
#define VERSION_HAS_UPDATE 					 VERSION_HAS_NOT_UPDATE + 1
#define VERSION_HAS_FORCE_UPDATE 					 VERSION_HAS_UPDATE + 1


#define FRIEND_BUG_LEVEL 					 0
#define FRIEND_BUG_TIME_RANGE_1 					 1
#define FRIEND_BUG_TIME_RANGE_2 					 2
#define FRIEND_BUG_TIME_RANGE_3 					 3
#define FRIEND_BUG_TIME_RANGE_4 					 4
#define FRIEND_BUG_TIME_RANGE_5 					 5
#define FRIEND_BUG_PERCENT_TIME_RANGE_1 					 6
#define FRIEND_BUG_PERCENT_TIME_RANGE_2 					 7
#define FRIEND_BUG_PERCENT_TIME_RANGE_3 					 8
#define FRIEND_BUG_PERCENT_TIME_RANGE_4 					 9
#define FRIEND_BUG_PERCENT_TIME_RANGE_5 					 10
#define FRIEND_BUG_NUM_MIN 					 11
#define FRIEND_BUG_NUM_MAX 					 12
#define FRIEND_BUG_PERCENT_FAKE_BUG 					 13
#define FRIEND_BUG_1 					 14
#define FRIEND_BUG_2 					 15
#define FRIEND_BUG_3 					 16
#define FRIEND_BUG_MAX 					 17


#define DECOR_ID 					 0
#define DECOR_NAME 					 1
#define DECOR_EXP_INCREASE 					 2
#define DECOR_TIME_DECREASE 					 3
#define DECOR_GOLD_UPGRADE 					 4
#define DECOR_PEARL_ID_NUM 					 5
#define DECOR_UPGRADE_RATIO 					 6
#define DECOR_GOLD_DEFAULT 					 7
#define DECOR_GOLD_MIN 					 8
#define DECOR_GOLD_MAX 					 9
#define DECOR_BUG_APPEAR_RATIO 					 10
#define DECOR_LEVEL_UNLOCK 					 11
#define DECOR_BLESSING_RATIO 					 12
#define DECOR_BAD_LUCK_RATIO 					 13
#define DECOR_COMBO_EXP_BONUS 					 14
#define DECOR_COMBO_TIME_BONUS 					 15
#define DECOR_COMBO_BUG_BONUS 					 16
#define DECOR_USE_DURATION 					 17
#define DECOR_APPRAISAL 					 18

#define DECOR_NAME_EN 					 19
#define DECOR_NAME_SC 					 20
#define DECOR_NAME_TC 					 21
#define DECOR_PROPERTY_MAX 					 22


#define APPRAISAL_MACHINE_ID 					 0
#define APPRAISAL_MACHINE_ID_0 					 APPRAISAL_MACHINE_ID + 1
#define APPRAISAL_MACHINE_ID_1 					 APPRAISAL_MACHINE_ID_0 + 1
#define APPRAISAL_MACHINE_ID_2 					 APPRAISAL_MACHINE_ID_1 + 1
#define APPRAISAL_MACHINE_ID_3 					 APPRAISAL_MACHINE_ID_2 + 1
#define APPRAISAL_MACHINE_ID_4 					 APPRAISAL_MACHINE_ID_3 + 1
#define APPRAISAL_MACHINE_ID_5 					 APPRAISAL_MACHINE_ID_4 + 1
#define APPRAISAL_MACHINE_ID_6 					 APPRAISAL_MACHINE_ID_5 + 1
#define APPRAISAL_MACHINE_ID_7 					 APPRAISAL_MACHINE_ID_6 + 1
#define APPRAISAL_MACHINE_ID_8 					 APPRAISAL_MACHINE_ID_7 + 1
#define APPRAISAL_MACHINE_ID_9 					 APPRAISAL_MACHINE_ID_8 + 1
#define APPRAISAL_MACHINE_ID_10 					 APPRAISAL_MACHINE_ID_9 + 1
#define APPRAISAL_MACHINE_ID_11 					 APPRAISAL_MACHINE_ID_10 + 1
#define APPRAISAL_MACHINE_ID_12 					 APPRAISAL_MACHINE_ID_11 + 1
#define APPRAISAL_MACHINE_ID_13 					 APPRAISAL_MACHINE_ID_12 + 1
#define APPRAISAL_MACHINE_ID_14 					 APPRAISAL_MACHINE_ID_13 + 1
#define APPRAISAL_MACHINE_ID_15 					 APPRAISAL_MACHINE_ID_14 + 1
#define APPRAISAL_MACHINE_ID_16 					 APPRAISAL_MACHINE_ID_15 + 1
#define APPRAISAL_MACHINE_ID_17 					 APPRAISAL_MACHINE_ID_16 + 1
#define APPRAISAL_MACHINE_ID_18 					 APPRAISAL_MACHINE_ID_17 + 1
#define APPRAISAL_MACHINE_ID_19 					 APPRAISAL_MACHINE_ID_18 + 1
#define APPRAISAL_MACHINE_MAX 					 APPRAISAL_MACHINE_ID_19 + 1


#define DAILY_GIFT_USER_LEVEL 					 0
#define DAILY_GIFT_PACK_1 					 DAILY_GIFT_USER_LEVEL + 1
#define DAILY_GIFT_PACK_2 					 DAILY_GIFT_PACK_1 + 1
#define DAILY_GIFT_PACK_3 					 DAILY_GIFT_PACK_2 + 1
#define DAILY_GIFT_PACK_4 					 DAILY_GIFT_PACK_3 + 1
#define DAILY_GIFT_PACK_5 					 DAILY_GIFT_PACK_4 + 1
#define DAILY_GIFT_PACK_6 					 DAILY_GIFT_PACK_5 + 1
#define DAILY_GIFT_PACK_7 					 DAILY_GIFT_PACK_6 + 1
#define DAILY_GIFT_PACK_8 					 DAILY_GIFT_PACK_7 + 1
#define DAILY_GIFT_PACK_9 					 DAILY_GIFT_PACK_8 + 1
#define DAILY_GIFT_PACK_10 					 DAILY_GIFT_PACK_9 + 1
#define DAILY_GIFT_PACK_11 					 DAILY_GIFT_PACK_10 + 1
#define DAILY_GIFT_PACK_12 					 DAILY_GIFT_PACK_11 + 1
#define DAILY_GIFT_PACK_13 					 DAILY_GIFT_PACK_12 + 1
#define DAILY_GIFT_PACK_14 					 DAILY_GIFT_PACK_13 + 1
#define DAILY_GIFT_PACK_15 					 DAILY_GIFT_PACK_14 + 1
#define DAILY_GIFT_PACK_MAX 					 DAILY_GIFT_PACK_15 + 1


#define FIRSTPAY_GIFT_PACK_1 					 0
#define FIRSTPAY_GIFT_PACK_2 					 1
#define FIRSTPAY_GIFT_PACK_3 					 2
#define FIRSTPAY_GIFT_PACK_4 					 3


#define GIFT_ALPHA_TEST_ID 					 0
#define GIFT_ALPHA_TEST_FB_ID 					 1
#define GIFT_ALPHA_TEST_ZING_ID 					 2
#define GIFT_ALPHA_TEST_DIAMOND_AMOUNT 					 3


#define CONSTANT_USER_LEVEL 					 0
#define CONSTANT_DO_PAID_UNLOCK 					 CONSTANT_USER_LEVEL + 1
#define CONSTANT_ORDER_CONTROL_ENOUGH 					 CONSTANT_DO_PAID_UNLOCK + 1
#define CONSTANT_ORDER_CONTROL_MISS 					 CONSTANT_ORDER_CONTROL_ENOUGH + 1
#define CONSTANT_ORDER_BUG_PEARL 					 CONSTANT_ORDER_CONTROL_MISS + 1
#define CONSTANT_ORDER_PEARL_RATE 					 CONSTANT_ORDER_BUG_PEARL + 1
#define CONSTANT_ORDER_BUG_RATE 					 CONSTANT_ORDER_PEARL_RATE + 1
#define CONSTANT_REPUTATION_COLLECT_MAX 					 CONSTANT_ORDER_BUG_RATE + 1
#define CONSTANT_NPC_MACHINE_CORRUPT 					 CONSTANT_REPUTATION_COLLECT_MAX + 1
#define CONSTANT_EXP_REPAIR_MACHINE 					 CONSTANT_NPC_MACHINE_CORRUPT + 1
#define CONSTANT_EXP_CATCH_BUG 					 CONSTANT_EXP_REPAIR_MACHINE + 1
#define CONSTANT_ITEM_PER_ORDER 					 CONSTANT_EXP_CATCH_BUG + 1
#define CONSTANT_ITEM_MAX 					 CONSTANT_ITEM_PER_ORDER + 1
#define CONSTANT_ITEM_PER_ORDER_BUG_PEARL 					 CONSTANT_ITEM_MAX + 1
#define CONSTANT_ITEM_MAX_ORDER_BUG_PEARL 					 CONSTANT_ITEM_PER_ORDER_BUG_PEARL + 1
#define CONSTANT_ITEM_MIN_ORDER_DAILY 					 CONSTANT_ITEM_MAX_ORDER_BUG_PEARL + 1
#define CONSTANT_ITEM_MAX_ORDER_DAILY 					 CONSTANT_ITEM_MIN_ORDER_DAILY + 1
#define CONSTANT_NEW_ORDER_WAIT_TIME 					 CONSTANT_ITEM_MAX_ORDER_DAILY + 1
#define CONSTANT_DAILY_ORDER_DIAMOND_RATIO 					 CONSTANT_NEW_ORDER_WAIT_TIME + 1
#define CONSTANT_DO_LETTER_1 					 CONSTANT_DAILY_ORDER_DIAMOND_RATIO + 1
#define CONSTANT_DO_LETTER_2 					 CONSTANT_DO_LETTER_1 + 1
#define CONSTANT_DO_LETTER_3 					 CONSTANT_DO_LETTER_2 + 1
#define CONSTANT_DO_LETTER_4 					 CONSTANT_DO_LETTER_3 + 1
#define CONSTANT_DO_LETTER_5 					 CONSTANT_DO_LETTER_4 + 1
#define CONSTANT_DO_LETTER_6 					 CONSTANT_DO_LETTER_5 + 1
#define CONSTANT_DO_FREE_GOLD_COEFFICIENT_RATE 					 CONSTANT_DO_LETTER_6 + 1
#define CONSTANT_DO_FREE_EXP_COEFFICIENT_RATE 					 CONSTANT_DO_FREE_GOLD_COEFFICIENT_RATE + 1
#define CONSTANT_DO_PAID_GOLD_COEFFICIENT_RATE 					 CONSTANT_DO_FREE_EXP_COEFFICIENT_RATE + 1
#define CONSTANT_DO_PAID_EXP_COEFFICIENT_RATE 					 CONSTANT_DO_PAID_GOLD_COEFFICIENT_RATE + 1
#define CONSTANT_DO_RANDOM_PLANT 					 CONSTANT_DO_PAID_EXP_COEFFICIENT_RATE + 1
#define CONSTANT_DO_PAID_ITEM_MIN 					 CONSTANT_DO_RANDOM_PLANT + 1
#define CONSTANT_DO_PAID_ITEM_MAX 					 CONSTANT_DO_PAID_ITEM_MIN + 1
#define CONSTANT_DO_BUG_PEARL_COEFFICIENT_RATE 					 CONSTANT_DO_PAID_ITEM_MAX + 1
#define CONSTANT_ORDER_PLANT_ITEM_MIN 					 CONSTANT_DO_BUG_PEARL_COEFFICIENT_RATE + 1
#define CONSTANT_ORDER_PLANT_ITEM_MAX 					 CONSTANT_ORDER_PLANT_ITEM_MIN + 1
#define CONSTANT_ITEM_PER_ORDER_PLANT 					 CONSTANT_ORDER_PLANT_ITEM_MAX + 1
#define CONSTANT_ORDER_PLANT 					 CONSTANT_ITEM_PER_ORDER_PLANT + 1
#define CONSTANT_OWL_POWER_LIMIT 					 CONSTANT_ORDER_PLANT + 1
#define CONSTANT_ORDER_ITEM_PLANT_PLUS 					 CONSTANT_OWL_POWER_LIMIT + 1
#define CONSTANT_NO_GOLD_COEFFICIENT_RATE 					 CONSTANT_ORDER_ITEM_PLANT_PLUS + 1
#define CONSTANT_NO_XP_COEFFICIENT_RATE 					 CONSTANT_NO_GOLD_COEFFICIENT_RATE + 1
#define CONSTANT_NO_ITEM_PRODUCT_RATE 					 CONSTANT_NO_XP_COEFFICIENT_RATE + 1
#define CONSTANT_PS_ITEM_EXPIRED_TIME 					 CONSTANT_NO_ITEM_PRODUCT_RATE + 1
#define CONSTANT_MAX_AIRSHIP_PER_DAY 					 CONSTANT_PS_ITEM_EXPIRED_TIME + 1
#define CONSTANT_AIRSHIP_MIN_ITEM_TYPE 					 CONSTANT_MAX_AIRSHIP_PER_DAY + 1
#define CONSTANT_AIRSHIP_MAX_ITEM_TYPE 					 CONSTANT_AIRSHIP_MIN_ITEM_TYPE + 1
#define CONSTANT_AIRSHIP_MIN_CARGO_NUM_PER_ITEM_TYPE 					 CONSTANT_AIRSHIP_MAX_ITEM_TYPE + 1
#define CONSTANT_AIRSHIP_MAX_CARGO_NUM_PER_ITEM_TYPE 					 CONSTANT_AIRSHIP_MIN_CARGO_NUM_PER_ITEM_TYPE + 1
#define CONSTANT_AIRSHIP_EASY_REQUEST 					 CONSTANT_AIRSHIP_MAX_CARGO_NUM_PER_ITEM_TYPE + 1
#define CONSTANT_AIRSHIP_MEDIUM_REQUEST 					 CONSTANT_AIRSHIP_EASY_REQUEST + 1
#define CONSTANT_AIRSHIP_HARD_REQUEST 					 CONSTANT_AIRSHIP_MEDIUM_REQUEST + 1
#define CONSTANT_AIRSHIP_MIN_NUM_REQUIRE_ITEM_EASY 					 CONSTANT_AIRSHIP_HARD_REQUEST + 1
#define CONSTANT_AIRSHIP_MAX_NUM_REQUIRE_ITEM_EASY 					 CONSTANT_AIRSHIP_MIN_NUM_REQUIRE_ITEM_EASY + 1
#define CONSTANT_AIRSHIP_MIN_NUM_REQUIRE_ITEM_MEDIUM 					 CONSTANT_AIRSHIP_MAX_NUM_REQUIRE_ITEM_EASY + 1
#define CONSTANT_AIRSHIP_MAX_NUM_REQUIRE_ITEM_MEDIUM 					 CONSTANT_AIRSHIP_MIN_NUM_REQUIRE_ITEM_MEDIUM + 1
#define CONSTANT_AIRSHIP_MIN_NUM_REQUIRE_ITEM_HARD 					 CONSTANT_AIRSHIP_MAX_NUM_REQUIRE_ITEM_MEDIUM + 1
#define CONSTANT_AIRSHIP_MAX_NUM_REQUIRE_ITEM_HARD 					 CONSTANT_AIRSHIP_MIN_NUM_REQUIRE_ITEM_HARD + 1
#define CONSTANT_FORTUNE_WHEEL_GOLD 					 CONSTANT_AIRSHIP_MAX_NUM_REQUIRE_ITEM_HARD + 1
#define CONSTANT_FORTUNE_WHEEL_NORMAL_BASIC_PRICE 					 CONSTANT_FORTUNE_WHEEL_GOLD + 1
#define CONSTANT_FORTUNE_WHEEL_LAST_BASIC_PRICE 					 CONSTANT_FORTUNE_WHEEL_NORMAL_BASIC_PRICE + 1
#define CONSTANT_AIRSHIP_REPUTATION 					 CONSTANT_FORTUNE_WHEEL_LAST_BASIC_PRICE + 1
#define CONSTANT_AIRSHIP_MIN_BONUS_GOLD 					 CONSTANT_AIRSHIP_REPUTATION + 1
#define CONSTANT_AIRSHIP_MAX_BONUS_GOLD 					 CONSTANT_AIRSHIP_MIN_BONUS_GOLD + 1
#define CONSTANT_AIRSHIP_MIN_BONUS_EXP 					 CONSTANT_AIRSHIP_MAX_BONUS_GOLD + 1
#define CONSTANT_AIRSHIP_MAX_BONUS_EXP 					 CONSTANT_AIRSHIP_MIN_BONUS_EXP + 1
#define CONSTANT_AIRSHIP_REPUTATION_REDUCE_PER_HOUR 					 CONSTANT_AIRSHIP_MAX_BONUS_EXP + 1
#define CONSTANT_PERCENT_DROP_MOONCAKE_CATCH_BUG 					 CONSTANT_AIRSHIP_REPUTATION_REDUCE_PER_HOUR + 1
#define CONSTANT_NUM_DROP_MOONCAKE 					 CONSTANT_PERCENT_DROP_MOONCAKE_CATCH_BUG + 1
#define CONSTANT_NUM_DROP_HALLOWEEN_1 					 CONSTANT_NUM_DROP_MOONCAKE + 1
#define CONSTANT_NUM_DROP_HALLOWEEN_2 					 CONSTANT_NUM_DROP_HALLOWEEN_1 + 1
#define CONSTANT_NUM_DROP_HALLOWEEN_3 					 CONSTANT_NUM_DROP_HALLOWEEN_2 + 1
#define CONSTANT_FORTUNE_FAKE_DIAMOND 					 CONSTANT_NUM_DROP_HALLOWEEN_3 + 1
#define CONSTANT_MAX 					 CONSTANT_FORTUNE_FAKE_DIAMOND + 1


#define OWL_SLOT_UNLOCK_DIAMOND 					 0
#define OWL_SLOT_UNLOCK_GOLD 					 OWL_SLOT_UNLOCK_DIAMOND + 1

#define OWL_SLOT_UNLOCK 					 0
#define OWL_SLOT_UNLOCK_DIAMOND_TYPE 					 1
#define OWL_SLOT_UNLOCK_GOLD_TYPE 					 2



#define GIFT_INFO 					 0
#define GIFT_INFO_ID 					 0
#define GIFT_INFO_NAME 					 1
#define GIFT_INFO_DESCRIPTION 					 2
#define GIFT_INFO_ITEMS_LIST 					 3

#define GIFT_INFO_NAME_EN 					 4
#define GIFT_INFO_DESCRIPTION_EN 					 5
#define GIFT_INFO_NAME_SC 					 6
#define GIFT_INFO_DESCRIPTION_SC 					 7
#define GIFT_INFO_NAME_TC 					 8
#define GIFT_INFO_DESCRIPTION_TC 					 9


#define GIFT_CONNECT_FB 					 0
#define GIFT_CONNECT_ZM 					 1
#define GIFT_LIKE_FB 					 3
#define GIFT_SHARE_FB 					 4
#define GIFT_CLOSED_USER 					 5
#define GIFT_FIRST_PAY 					 6
#define GIFT_CONNECT_ZALO 					 29



#define NOTIFY_TEXT_ID 					 0
#define NOTIFY_TEXT_TITLE 					 NOTIFY_TEXT_ID + 1
#define NOTIFY_TEXT_DESCRIPTION 					 NOTIFY_TEXT_TITLE + 1

#define NOTIFY_TEXT_TITLE_EN 					 NOTIFY_TEXT_DESCRIPTION + 1
#define NOTIFY_TEXT_DESCRIPTION_EN 					 NOTIFY_TEXT_TITLE_EN + 1
#define NOTIFY_TEXT_TITLE_SC 					 NOTIFY_TEXT_DESCRIPTION_EN + 1
#define NOTIFY_TEXT_DESCRIPTION_SC 					 NOTIFY_TEXT_TITLE_SC + 1
#define NOTIFY_TEXT_TITLE_TC 					 NOTIFY_TEXT_DESCRIPTION_SC + 1
#define NOTIFY_TEXT_DESCRIPTION_TC 					 NOTIFY_TEXT_TITLE_TC + 1

#define NOTIFY_SERVER_OVERLOADED 					 0
#define NOTIFY_SERVER_MAINTAINED 					 1
#define NOTIFY_NEW_UPDATE 					 9


#define SHEET_GIFT_CODE 					 0

#define GIFT_CODE_ID 					 0
#define GIFT_CODE_TYPE 					 GIFT_CODE_ID + 1
#define GIFT_CODE_CODE 					 GIFT_CODE_TYPE + 1
#define GIFT_CODE_NAME 					 GIFT_CODE_CODE + 1
#define GIFT_CODE_DESCRIPTION 					 GIFT_CODE_NAME + 1
#define GIFT_CODE_GIFT 					 GIFT_CODE_DESCRIPTION + 1
#define GIFT_CODE_START_TIME 					 GIFT_CODE_GIFT + 1
#define GIFT_CODE_END_TIME 					 GIFT_CODE_START_TIME + 1

#define GIFT_CODE_USE_TIME 					 GIFT_CODE_END_TIME + 1


#define EVENT_ID 					 0
#define EVENT_NAME 					 EVENT_ID + 1
#define EVENT_START 					 EVENT_NAME + 1
#define EVENT_END 					 EVENT_START + 1
#define EVENT_START_BEFORE 					 EVENT_END + 1
#define EVENT_END_BEFORE 					 EVENT_START_BEFORE + 1
#define EVENT_EMO_ID 					 EVENT_END_BEFORE + 1

#define EVENT_NAME_EN 					 EVENT_EMO_ID + 1
#define EVENT_NAME_SC 					 EVENT_NAME_EN + 1
#define EVENT_NAME_TC 					 EVENT_NAME_SC + 1
#define EVENT_MAX 					 EVENT_NAME_TC + 1


#define EMO_ID 					 0
#define EMO_NAME 					 EMO_ID + 1
#define EMO_APPEAR_RATIO 					 EMO_NAME + 1
#define EMO_POS 					 EMO_APPEAR_RATIO + 1
#define EMO_HIT_COUNT 					 EMO_POS + 1
#define EMO_RESET_HIT_FLAG 					 EMO_HIT_COUNT + 1
#define EMO_EMI_ID 					 EMO_RESET_HIT_FLAG + 1
#define EMO_FIRST_ACTION 					 EMO_EMI_ID + 1
#define EMO_LAST_ACTION 					 EMO_FIRST_ACTION + 1
#define EMO_HIT_ACTION 					 EMO_LAST_ACTION + 1
#define EMO_SPRITE_ID 					 EMO_HIT_ACTION + 1

#define EMO_NAME_EN 					 EMO_SPRITE_ID + 1
#define EMO_NAME_SC 					 EMO_NAME_EN + 1
#define EMO_NAME_TC 					 EMO_NAME_SC + 1
#define EMO_MAX 					 EMO_NAME_TC + 1


#define EMI_ID 					 0
#define EMI_NAME 					 EMI_ID + 1
#define EMI_DESCRIPTION 					 EMI_NAME + 1
#define EMI_DIAMOND_BUY 					 EMI_DESCRIPTION + 1
#define EMI_GOLD_DEFAULT 					 EMI_DIAMOND_BUY + 1
#define EMI_GOLD_MIN 					 EMI_GOLD_DEFAULT + 1
#define EMI_GOLD_MAX 					 EMI_GOLD_MIN + 1
#define EMI_STOCK_ID 					 EMI_GOLD_MAX + 1
#define EMI_ANIM_ID 					 EMI_STOCK_ID + 1

#define EMI_NAME_EN 					 EMI_ANIM_ID + 1
#define EMI_DESCRIPTION_EN 					 EMI_NAME_EN + 1
#define EMI_NAME_SC 					 EMI_DESCRIPTION_EN + 1
#define EMI_DESCRIPTION_SC 					 EMI_NAME_SC + 1
#define EMI_NAME_TC 					 EMI_DESCRIPTION_SC + 1
#define EMI_DESCRIPTION_TC 					 EMI_NAME_TC + 1
#define EMI_MAX 					 EMI_DESCRIPTION_TC + 1


#define MERCHANT_LEVEL 					 0
#define MERCHANT_LIST_SIZE 					 1
#define MERCHANT_APPEAR_TIME 					 2
#define MERCHANT_MIN_PERCENT 					 3
#define MERCHANT_MAX_PERCENT 					 4
#define MERCHANT_MAX_REQUEST_NUM_STOCK_SILO 					 5
#define MERCHANT_PRICE_RATIO_STOCK_SILO 					 6
#define MERCHANT_MAX_REQUEST_NUM_STOCK_BARN 					 7
#define MERCHANT_PRICE_RATIO_STOCK_BARN 					 8
#define MERCHANT_GOLD_TO_ITEM 					 9
#define MERCHANT_MAX 					 10


#define FEED_ID 					 0
#define FEED_KEY 					 1
#define FEED_TITLE 					 2
#define FEED_DESCRIPTION 					 3
#define FEED_LINK 					 4
#define FEED_IMG_LINK 					 5
#define FEED_CAPTION 					 6

#define FEED_TITLE_EN 					 7
#define FEED_DESCRIPTION_EN 					 8
#define FEED_TITLE_SC 					 9
#define FEED_DESCRIPTION_SC 					 10
#define FEED_TITLE_TC 					 11
#define FEED_DESCRIPTION_TC 					 12
#define FEED_MAX 					 13


#define CDN_PLATFORM 					 0
#define CDN_RESOLUTION 					 CDN_PLATFORM + 1
#define CDN_DISTRIBUTOR 					 CDN_RESOLUTION + 1
#define CDN_NEWEST_VERSION 					 CDN_DISTRIBUTOR + 1
#define CDN_LINK 					 CDN_NEWEST_VERSION + 1
#define CDN_SPRITE_ID 					 CDN_LINK + 1
#define CDN_NAME 					 CDN_SPRITE_ID + 1
#define CDN_MD5 					 CDN_NAME + 1
#define CDN_TYPE 					 CDN_MD5 + 1
#define CDN_ID 					 CDN_TYPE + 1
#define CDN_ACTIVE 					 CDN_ID + 1
#define CDN_MAX 					 CDN_ACTIVE + 1


#define EVENT_GLOBAL_ID 					 0
#define EVENT_GLOBAL_NAME 					 EVENT_GLOBAL_ID + 1
#define EVENT_GLOBAL_START_DATE 					 EVENT_GLOBAL_NAME + 1
#define EVENT_GLOBAL_END_DATE 					 EVENT_GLOBAL_START_DATE + 1
#define EVENT_GLOBAL_BONUS_EXP_RATE 					 EVENT_GLOBAL_END_DATE + 1
#define EVENT_GLOBAL_BONUS_GOLD_RATE 					 EVENT_GLOBAL_BONUS_EXP_RATE + 1


#define AIRSHIP_ID 					 0
#define AIRSHIP_REQUIRE_LEVEL 					 1
#define AIRSHIP_REQUIRE_ITEMS 					 2
#define AIRSHIP_UNLOCK_DURATION 					 3
#define AIRSHIP_STAY_DURATION 					 4
#define AIRSHIP_LEAVE_DURATION 					 5
#define AIRSHIP_MIN_POINT 					 6
#define AIRSHIP_MAX_POINT 					 7
#define AIRSHIP_HELP_TIME 					 8
#define AIRSHIP_MIN_BONUS_GOLD 					 9
#define AIRSHIP_MAX_BONUS_GOLD 					 10
#define AIRSHIP_MIN_BONUS_EXP 					 11
#define AIRSHIP_MAX_BONUS_EXP 					 12
#define AIRSHIP_POINT_REDUCE 					 13
#define AIRSHIP_MIN_REPUTATION 					 14
#define AIRSHIP_MAX_REPUTATION 					 15
#define AIRSHIP_REPUTATION_REDUCE 					 16


#define ITEM_VALUE_INDEX 					 0
#define ITEM_VALUE_NAME 					 1
#define ITEM_VALUE_EXP 					 2
#define ITEM_VALUE_GOLD 					 3
#define ITEM_VALUE_REPUTATION 					 4
#define ITEM_TOMKID_GOLD_BASIC 					 5
#define ITEM_TOMKID_MIN_NUM_PACK_1 					 6
#define ITEM_TOMKID_MAX_NUM_PACK_1 					 7
#define ITEM_TOMKID_MIN_RATIO_PACK_1 					 8
#define ITEM_TOMKID_MAX_RATIO_PACK_1 					 9
#define ITEM_TOMKID_MIN_NUM_PACK_2 					 10
#define ITEM_TOMKID_MAX_NUM_PACK_2 					 11
#define ITEM_TOMKID_MIN_RATIO_PACK_2 					 12
#define ITEM_TOMKID_MAX_RATIO_PACK_2 					 13
#define ITEM_TOMKID_MIN_NUM_PACK_3 					 14
#define ITEM_TOMKID_MAX_NUM_PACK_3 					 15
#define ITEM_TOMKID_MIN_RATIO_PACK_3 					 16
#define ITEM_TOMKID_MAX_RATIO_PACK_3 					 17
#define ITEM_FORTUNE_WHEEL_REAL_RATIO 					 18
#define ITEM_FORTUNE_WHEEL_FAKE_RATIO 					 19


#define TOMKID_INDEX 					 0
#define TOMKID_LEVEL_UNLOCK 					 1
#define TOMKID_FIRST_USE_DURATION 					 2
#define TOMKID_LONG_REST_DURATION 					 3
#define TOMKID_SHORT_REST_DURATION 					 4
#define TOMKID_DIAMOND_1_DAY 					 5
#define TOMKID_DIAMOND_3_DAY 					 6
#define TOMKID_DIAMOND_7_DAY 					 7


#define ROTA_FORTUNAE_INDEX 					 0
#define ROTA_FORTUNAE_PAID_OR_FREE 					 1
#define ROTA_FORTUNAE_DIAMOND_RATIO 					 2


#define ROTA_FORTUNAE_FREE_1 					 0
#define ROTA_FORTUNAE_PAID_1 					 1
#define ROTA_FORTUNAE_PAID_2 					 2
#define ROTA_FORTUNAE_PAID_3 					 3
#define ROTA_FORTUNAE_PAID_4 					 4
#define ROTA_FORTUNAE_PAID_5 					 5
#define ROTA_FORTUNAE_FREE_2 					 6


#define INVITE_FRIEND_ID 					 0
#define INVITE_FRIEND_NUM_REQUIRED 					 1
#define INVITE_FRIEND_GIFT 					 2


#define EVENT_MID_AUTUMN_ID 					 0
#define EVENT_MID_AUTUMN_NAME 					 1
#define EVENT_MID_AUTUMN_GIFT_ITEM 					 2
#define EVENT_MID_AUTUMN_NUM_REQUIRE 					 3
#define EVENT_MID_AUTUMN_NAME_EN 					 4
#define EVENT_MID_AUTUMN_HINT_1 					 5
#define EVENT_MID_AUTUMN_HINT_2 					 6
#define EVENT_MID_AUTUMN_HINT_1_EN 					 7
#define EVENT_MID_AUTUMN_HINT_2_EN 					 8
#define EVENT_MID_AUTUMN_TOTAL 					 9


#define ROTA_FORTUNAE_FREE_1_1ST_RETRY 					 7
#define ROTA_FORTUNAE_PAID_1_1ST_RETRY 					 8
#define ROTA_FORTUNAE_PAID_2_1ST_RETRY 					 9
#define ROTA_FORTUNAE_PAID_3_1ST_RETRY 					 10
#define ROTA_FORTUNAE_PAID_4_1ST_RETRY 					 11
#define ROTA_FORTUNAE_PAID_5_1ST_RETRY 					 12
#define ROTA_FORTUNAE_FREE_2_1ST_RETRY 					 13


#define ROTA_FORTUNAE_FREE_1_2ND_RETRY 					 14
#define ROTA_FORTUNAE_PAID_1_2ND_RETRY 					 15
#define ROTA_FORTUNAE_PAID_2_2ND_RETRY 					 16
#define ROTA_FORTUNAE_PAID_3_2ND_RETRY 					 17
#define ROTA_FORTUNAE_PAID_4_2ND_RETRY 					 18
#define ROTA_FORTUNAE_PAID_5_2ND_RETRY 					 19
#define ROTA_FORTUNAE_FREE_2_2ND_RETRY 					 20


#define ROTA_FORTUNAE_FREE_1_3RD_RETRY 					 21
#define ROTA_FORTUNAE_PAID_1_3RD_RETRY 					 22
#define ROTA_FORTUNAE_PAID_2_3RD_RETRY 					 23
#define ROTA_FORTUNAE_PAID_3_3RD_RETRY 					 24
#define ROTA_FORTUNAE_PAID_4_3RD_RETRY 					 25
#define ROTA_FORTUNAE_PAID_5_3RD_RETRY 					 26
#define ROTA_FORTUNAE_FREE_2_3RD_RETRY 					 27


#define COMBO_ID 					 0
#define COMBO_NAME 					 1
#define COMBO_REQUIRE 					 2
#define COMBO_BONUS_PLANT_EXP 					 3
#define COMBO_BONUS_PLANT_TIME 					 4
#define COMBO_BONUS_BUG 					 5
#define COMBO_BONUS_AIRSHIP_GOLD 					 6
#define COMBO_BONUS_AIRSHIP_EXP 					 7
#define COMBO_BONUS_ORDER_NORMAL 					 8
#define COMBO_BONUS_ORDER_DAILY 					 9


#define DROP_CUSTOM_ID 					 0
#define DROP_CUSTOM_ITEM 					 1
#define DROP_CUSTOM_LEVEL 					 2


#define GIFT_CODE_ENTER_MAX 					 5

#define MAX_SLOT_PER_FLOOR 					 6
#define SLOT_TUTORIAL 					 6

#define STOCK_SILO 					 0
#define STOCK_BARN 					 1
#define STOCK_WAREHOUSE 					 2
#define STOCK_EVENT 					 3

#define MACHINE_LOCK 					 0
#define MACHINE_UNLOCK 					 MACHINE_LOCK + 1
#define MACHINE_READY 					 MACHINE_UNLOCK + 1

#define MACHINE_DURABILITY_ADD 					 10
#define MACHINE_SLOT_MAX 					 16
#define MACHINE_DEFAULT_STOCK_CAPACITY 					 13

#define MACHINE_STATUS_PROCESSING 					 1
#define MACHINE_STATUS_COMPLETED 					 MACHINE_STATUS_PROCESSING + 1

#define FLOOR_MAX 					 20
#define STOCK_MAX 					 3


#define ORDER_NORMAL 					 0
#define ORDER_DAILY 					 ORDER_NORMAL + 1
#define ORDER_EVENT 					 ORDER_DAILY + 1
#define ORDER_TYPE_MAX 					 ORDER_EVENT + 1

#define ORDER_DAILY_INDEX 					 4 // start from 0
#define ORDER_MAX 					 9

#define NEW_DAILY_ORDER_PAID_WAIT_TIME 					 3 * 60 // 3 minutes

#define USER_LEVEL_ORDER_CONTROL 					 10
#define USER_LEVEL_ORDER_BUG_PEARL 					 8

#define ORDER_LETTER_COUNT 					 6

#define NPC_SNOW_WHITE_ID 					 0 // follow client data
#define NPC_FROG_PRINCE_ID 					 2 // follow client data
#define NPC_TINKER_BELL_ID 					 3 // follow client data

#define ORDER_RANDOM_ITEM_FOLLOW_USER_STOCK 					 0
#define ORDER_RANDOM_ITEM 					 1
#define ORDER_RANDOM_BUG_AND_PEARL 					 2

#define MAX_FLOOR_ON_SCREEN 					 2

#define GOLD_ID 					 0
#define DIAMOND_ID 					 1
#define REPUTATION_ID 					 2
#define EXP_ID 					 3
#define EXP_GIFT 					 6

#define NPC_MAX 					 10

#define IT_GAMEITEM 					 -1
#define IT_POT 					 0
#define IT_PLANT 					 1
#define IT_BUILDING 					 2
#define IT_BUG 					 3
#define IT_PRODUCT 					 4
#define IT_MONEY 					 5
#define IT_COUNT 					 6
#define IT_DECOR 					 7
#define IT_MATERIAL 					 8
#define IT_EMO 					 9
#define IT_EMI 					 10
#define IT_CLOUD_FLOOR 					 12
#define IT_EVENT 					 13


#define APPRAISAL_POT 					 0
#define APPRAISAL_FLOOR 					 1
#define APPRAISAL_MACHINE 					 2
#define APPRAISAL_STOCK 					 3
#define APPRAISAL_DECOR 					 4


#define SHARE_FB_LEVEL_UP 					 0


#define PRIVATE_SHOP_MAX_SLOT 					 20
#define PRIVATE_SHOP_DEFAULT_SLOT_NUMBER 					 2
#define PRIVATE_SHOP_START_SLOT_FRIEND 					 2
#define PRIVATE_SHOP_NUMBER_OF_SLOT_FRIEND 					 4
#define PRIVATE_SHOP_START_SLOT_DIAMOND 					 6
#define PRIVATE_SHOP_ADS_PENDING_DURATION 					 5 // minutes
#define PRIVATE_SHOP_LOCK_EXPIRED_DURATION 					 1 // after 12 seconds, the lock (if any) will be automatically unlocked.
#define PRIVATE_SHOP_ADS_MAX_TIME 					 3 * 60 * 60 // 3 hours
#define PRIVATE_SHOP_ITEM_EXPIRE_TIME 					 24 * 60 * 60


#define NPC_SHOP_REFRESH_TIME 					 24 * 60 * 60 // once a day
#define NPC_SHOP_NUM_ITEM_SELL 					 6


#define MAGIC_WATER_BOTTLE_DROP_RATIO 					 10
#define MACHINE_REDUCE_GOLD_MAINTAIN_RATIO 					 10
#define MACHINE_DATA_LOCK_TIME 					 5


#define PS_ITEM_STATUS_EMPTY 					 0
#define PS_ITEM_STATUS_SELLING 					 1
#define PS_ITEM_STATUS_SOLD 					 2
#define PS_ITEM_EXPIRING 					 3
#define PS_ITEM_EXPIRED 					 4


#define NEWS_BOARD_MAX_SLOT 					 36
#define NEWS_BOARD_ADS_MAX_TIME 					 5 * 60//5 * 60 // 5 minutes
#define NEWS_BOARD_REFRESH_TIME 					 1 * 60 * 60//3 * 60 * 60 // 3 hours
#define NEWS_BOARD_REFRESH_PRICE 					 1


#define MAX_GIFT_DAILY_NUM 					 4


#define ACTION_HARVEST_PLANT 					 2
#define ACTION_HARVEST_PRODUCT 					 3
#define ACTION_REPAIR_FRIEND_MACHINE 					 4


#define MERCHANT_RED_HOOD 					 0
#define MERCHANT_PUSS_IN_BOOST 					 1
#define MERCHANT_GROUCHY 					 2
#define MERCHANT_MAX_CONCURRENT 					 2


#define RANKING_SIZE 					 3
#define SORT_INTERVAL 					 10 // seconds


#define AIRSHIP_LOCKED 					 -1
#define AIRSHIP_PENDING 					 0
#define AIRSHIP_UNLOCKED 					 1
#define AIRSHIP_LANDING 					 2
#define AIRSHIP_DEPARTING 					 3
#define AIRSHIP_FULL 					 4
#define AIRSHIP_LOCK_TIME 					 5
#define AIRSHIP_MAX_HELP 					 3


#define TOMKID_LOCKED 					 -1
#define TOMKID_READY 					 0
#define TOMKID_LONG_REST 					 1
#define TOMKID_SHORT_REST 					 2
#define TOMKID_NOT_HIRED 					 3
#define TOMKID_RESTING 					 4
#define TOMKID_PROVIDING_GOODS 					 5
#define TOMKID_DEFAULT_SUGGEST_NUM 					 3
#define TOMKID_HIRE_PACK_1 					 1
#define TOMKID_HIRE_PACK_2 					 2
#define TOMKID_HIRE_PACK_3 					 3



#define OFFER_USER_GROUP_UNPAID 					 0
#define OFFER_USER_GROUP_PAID_LESS_10 					 1
#define OFFER_USER_GROUP_PAID_LESS_20 					 2
#define OFFER_USER_GROUP_PAID_LESS_30 					 3
#define OFFER_USER_GROUP_PAID_LESS_40 					 4
#define OFFER_USER_GROUP_PAID_LESS_50 					 5
#define OFFER_USER_GROUP_PAID_LESS_60 					 6
#define OFFER_USER_GROUP_PAID_LESS_70 					 7
#define OFFER_USER_GROUP_PAID_LESS_80 					 8
#define OFFER_USER_GROUP_PAID_LESS_90 					 9
#define OFFER_USER_GROUP_PAID_LESS_100 					 10
#define OFFER_USER_GROUP_PAID_LESS_150 					 11
#define OFFER_USER_GROUP_PAID 					 12
#define OFFER_USER_GROUP_NEW_REG 					 13

#define OFFER_START 					 1
#define OFFER_END 					 2
#define OFFER_DURA 					 3
#define OFFER_NAME 					 4
#define OFFER_DESCRIPTION 					 5
#define OFFER_LINK_IMAGE 					 6
#define OFFER_MD5_IMAGE 					 7
#define OFFER_CONTENT_DIAMOND 					 8
#define OFFER_CONTENT_GOLD 					 9
#define OFFER_CONTENT_CASHIN 					 10
#define OFFER_CONTENT_SALE_OFF 					 11
#define OFFER_CONTENT_TOM_KID 					 12
#define OFFER_BUTTON_LABEL 					 13
#define OFFER_WEB_LINK 					 14
#define OFFER_AVAILABLE_TIME 					 15


#define USER_MATERIAL_UNLOCK 					 USER_PROD_ID_UNLOCK + 1
#define USER_BUG_UNLOCK 					 USER_MATERIAL_UNLOCK + 1
#define USER_DECOR_UNLOCK 					 USER_BUG_UNLOCK + 1


// #define OFFER_PACK_UNPAID 					 0
// #define OFFER_PACK_PAID 					 1
// #define OFFER_PACK_PAID_LESS_10 					 10
// #define OFFER_PACK_PAID_LESS_20 					 20
// #define OFFER_PACK_PAID_LESS_30 					 30
// #define OFFER_PACK_PAID_LESS_40 					 40
// #define OFFER_PACK_PAID_LESS_50 					 50
// #define OFFER_PACK_PAID_LESS_60 					 60
// #define OFFER_PACK_PAID_LESS_70 					 70
// #define OFFER_PACK_PAID_LESS_80 					 80
// #define OFFER_PACK_PAID_LESS_90 					 90
// #define OFFER_PACK_PAID_LESS_100 					 100
// #define OFFER_PACK_PAID_LESS_150 					 150


#define FEATURE_RANKING_VERSION 					 146
#define FEATURE_REFRESH_NEWSBOARD 					 147


#define PAYMENT_TYPE_LOCAL 					 0
#define PAYMENT_TYPE_IAP 					 1
#define PAYMENT_TYPE_ALL 					 2


#define RESULT_PER_LEVEL 					 200


#define NOTIFY_TYPE_MACHINE 					 0
#define NOTIFY_TYPE_AIRSHIP 					 1

#define NOTIFY_INDEX_DEFAULT 					 0
#define NOTIFY_INDEX_MACHINE_0 					 1
#define NOTIFY_INDEX_MACHINE_1 					 2
#define NOTIFY_INDEX_MACHINE_2 					 3
#define NOTIFY_INDEX_MACHINE_3 					 4
#define NOTIFY_INDEX_MACHINE_4 					 5
#define NOTIFY_INDEX_MACHINE_5 					 6
#define NOTIFY_INDEX_MACHINE_6 					 7
#define NOTIFY_INDEX_MACHINE_7 					 8
#define NOTIFY_INDEX_MACHINE_8 					 9
#define NOTIFY_INDEX_MACHINE_9 					 10
#define NOTIFY_INDEX_MACHINE_10 					 11
#define NOTIFY_INDEX_MACHINE_11 					 12
#define NOTIFY_INDEX_MACHINE_12 					 13
#define NOTIFY_INDEX_MACHINE_13 					 14
#define NOTIFY_INDEX_MACHINE_14 					 15
#define NOTIFY_INDEX_MACHINE_15 					 16
#define NOTIFY_INDEX_MACHINE_16 					 17
#define NOTIFY_INDEX_MACHINE_17 					 18
#define NOTIFY_INDEX_MACHINE_18 					 19
#define NOTIFY_INDEX_MACHINE_19 					 20
#define NOTIFY_INDEX_AIRSHIP 					 21


#define EVENT_MARKER_TOM 					 (1<<0)
#define EVENT_MARKER_FORTUNE_WHEEL 					 (1<<1)
#define EVENT_MARKER_DAILY_ORDER 					 (1<<2)
#define EVENT_MARKER_AIRSHIP 					 (1<<3)


#define BONUS_PLANT 					 (1<<0)
#define BONUS_ORDER_DAILY 					 (1<<1)
#define BONUS_ORDER_NORMAL 					 (1<<2)
#define BONUS_AIRSHIP_GOLD 					 (1<<3)
#define BONUS_AIRSHIP_EXP 					 (1<<4)
#define BONUS_TOM 					 (1<<5)
#define BONUS_FORTUNE_WHEEL 					 (1<<6)
#define BONUS_MACHINE_TIME 					 (1<<7)
#define BONUS_MACHINE_EXP 					 (1<<8)
#define BONUS_MACHINE_GOLD 					 (1<<9)
#define BONUS_MACHINE_UPGRADE 					 (1<<10)
#define BONUS_POT_TIME 					 (1<<11)
#define BONUS_POT_EXP 					 (1<<12)
#define BONUS_POT_GOLD 					 (1<<13)
#define BONUS_POT_BUG 					 (1<<14)
#define BONUS_POT_UPGRADE 					 (1<<15)
#define BONUS_MERCHANT 					 (1<<16)

#define FEATURE_ID_TOM 					 0
#define FEATURE_ID_FORTUNE_WHEEL 					 1
#define FEATURE_ID_ORDER 					 2
#define FEATURE_ID_AIRSHIP 					 3
#define FEATURE_ID_FIRST_LOGIN 					 4

#define ORDER_NORMAL_ITEM_EVENT_NUM 					 0


#define ORDER_EVENT_LEVEL 					 0
#define ORDER_EVENT_REQUIRE_ITEMS 					 1
#define ORDER_EVENT_REWARD_ITEMS 					 2
#define ORDER_EVENT_BASIC_GOLD 					 3
#define ORDER_EVENT_BASIC_EXP 					 4

#define ORDER_EVENT_SLOT_INDEX 					 8


#define OPEN_EVENT_ITEM_INDEX 					 0
#define OPEN_EVENT_ITEM_NAME 					 1
#define OPEN_EVENT_ITEM_PERCENT_GROUP_0 					 2


#define CLOSE_FRIEND_LEVEL 					 0
#define CLOSE_FRIEND_MY_GIFT 					 1
#define CLOSE_FRIEND_GIFT 					 2


#define TREASURE_TRUNK_IDX 					 0
#define TREASURE_TRUNK_ITEM 					 1
#define TREASURE_TRUNK_COUNT_0 					 2
#define TREASURE_TRUNK_COUNT_1 					 3
#define TREASURE_TRUNK_COUNT_2 					 4
#define TREASURE_TRUNK_COUNT_3 					 5
#define TREASURE_TRUNK_COUNT_4 					 6
#define TREASURE_TRUNK_COUNT_5 					 7
#define TREASURE_TRUNK_COUNT_6 					 8


#define GEO_IP_IDX 					 0
#define GEO_IP_FROM 					 1
#define GEO_IP_TO 					 2
#define GEO_IP_LONG_FROM 					 3
#define GEO_IP_LONG_TO 					 4
#define GEO_IP_COUNTRY_CODE 					 5
#define GEO_IP_COUNTRY_NAME 					 6


#define PRODUCT_ID_BORUA 					 1 // bo rua
#define PRODUCT_ID_DOMDOM 					 4 // dom dom
#define PRODUCT_ID_OCSEN 					 9 // oc sen
#define PRODUCT_ID_NGOCDO 					 10 // ngoc do
#define PRODUCT_ID_NGOCVANG 					 11 // ngoc vang
#define PRODUCT_ID_NGOCXANHBIEN 					 12 // ngoc xanh bien
#define PRODUCT_ID_NGOCCAM 					 26 // ngoc cam
#define PRODUCT_ID_NGOCTIM 					 33 // ngoc tim
#define PRODUCT_ID_NGOCXANHLA 					 35 // ngoc xanh la
#define PRODUCT_ID_HATHUONGDUONG 					 18 // hat huong duong
#define PRODUCT_ID_CHUONCHUON 					 64
#define PRODUCT_ID_BUOM 					 65
#define PRODUCT_ID_ONG 					 66
#define PRODUCT_ID_BINHSUA 					 67
#define PRODUCT_ID_BANHDONU 					 68
#define PRODUCT_ID_KEOCHANH 					 69

#define MATERIAL_GACH 					 0
#define MATERIAL_SON_DO 					 1
#define MATERIAL_GO 					 2
#define MATERIAL_DA 					 3
#define MATERIAL_SON_VANG 					 4
#define MATERIAL_DINH 					 5
#define MATERIAL_NGOI 					 6
#define MATERIAL_SON_DEN 					 7
#define MATERIAL_SAT 					 8
#define MATERIAL_MAGIC_WATER_BOTTLE 					 9
#define MATERIAL_PROTECT_AMULET 					 10
#define MATERIAL_LUCKY_LEAF_RED_SMALL 					 11
#define MATERIAL_LUCKY_LEAF_RED_MEDIUM 					 12
#define MATERIAL_LUCKY_LEAF_RED_LARGE 					 13
#define MATERIAL_LUCKY_LEAF_PURPLE_SMALL 					 14
#define MATERIAL_LUCKY_LEAF_PURPLE_MEDIUM 					 15
#define MATERIAL_LUCKY_LEAF_PURPLE_LARGE 					 16
#define MATERIAL_LUCKY_LEAF_YELLOW_SMALL 					 17
#define MATERIAL_LUCKY_LEAF_YELLOW_MEDIUM 					 18
#define MATERIAL_LUCKY_LEAF_YELLOW_LARGE 					 19
#define MATERIAL_LUCKY_LEAF_GREEN_SMALL 					 20
#define MATERIAL_LUCKY_LEAF_GREEN_MEDIUM 					 21
#define MATERIAL_LUCKY_LEAF_GREEN_LARGE 					 22
#define MATERIAL_LUCKY_LEAF_BLUE_SMALL 					 23
#define MATERIAL_LUCKY_LEAF_BLUE_MEDIUM 					 24
#define MATERIAL_LUCKY_LEAF_BLUE_LARGE 					 25
#define MATERIAL_NET_ID 					 26
#define MATERIAL_CLOUD_CLUE 					 27
#define MATERIAL_LONG_HANDNET 					 28
#define MATERIAL_FERTILIZER_1 					 29
#define MATERIAL_FERTILIZER_2 					 30
#define MATERIAL_FERTILIZER_3 					 31
#define MATERIAL_LUCKY_LEAF_PURPLE_SUPER_LARGE 					 32
#define MATERIAL_LUCKY_LEAF_GREEN_SUPER_LARGE 					 33
#define MATERIAL_LUCKY_LEAF_GREEN_34 					 34
#define MATERIAL_LUCKY_LEAF_GREEN_35 					 35
#define MATERIAL_LUCKY_LEAF_GREEN_36 					 36
#define MATERIAL_LUCKY_LEAF_GREEN_37 					 37
#define MATERIAL_LUCKY_LEAF_GREEN_38 					 38
#define MATERIAL_LUCKY_LEAF_PURPLE_39 					 39
#define MATERIAL_LUCKY_LEAF_PURPLE_40 					 40
#define MATERIAL_LUCKY_LEAF_PURPLE_41 					 41
#define MATERIAL_LUCKY_LEAF_PURPLE_42 					 42
#define MATERIAL_LUCKY_LEAF_PURPLE_43 					 43
#define MATERIAL_MOON_CAKE 					 44
#define MATERIAL_ITEM_EVENT_HALLOWEEN_1 					 45
#define MATERIAL_ITEM_EVENT_HALLOWEEN_2 					 46
#define MATERIAL_ITEM_EVENT_HALLOWEEN_3 					 47
#define MATERIAL_ITEM_EVENT_HALLOWEEN_4 					 48
#define MATERIAL_ITEM_EVENT_FLOWER_20_11 					 49
#define MATERIAL_ITEM_EVENT_XMAS_2014_1 					 50
#define MATERIAL_ITEM_EVENT_XMAS_2014_2 					 51
#define MATERIAL_ITEM_EVENT_XMAS_2014_3 					 52
#define MATERIAL_ITEM_EVENT_XMAS_2014_4 					 53
#define MATERIAL_ITEM_XMAS_TREE_2014 					 54
#define MATERIAL_ITEM_BANH_CHUNG 					 55
#define MATERIAL_ITEM_BAO_LIXI_NORMAL 					 56
#define MATERIAL_ITEM_BAO_LIXI_SILVER 					 57
#define MATERIAL_ITEM_BAO_LIXI_GOLD 					 58
#define MATERIAL_ITEM_GLASS_ROSE 					 59
#define MATERIAL_ITEM_TRUNK_BRONZE 					 60
#define MATERIAL_ITEM_TRUNK_SILVER 					 61
#define MATERIAL_ITEM_TRUNK_GOLD 					 62
#define MATERIAL_ITEM_KEY_BRONZE 					 63
#define MATERIAL_ITEM_KEY_SILVER 					 64
#define MATERIAL_ITEM_KEY_GOLD 					 65
#define MATERIAL_ITEM_CANDLE 					 66


#define ITEM_EVENT_MOON_CAKE 					 0
#define ITEM_EVENT_HALLOWEEN_1 					 1
#define ITEM_EVENT_HALLOWEEN_2 					 2
#define ITEM_EVENT_HALLOWEEN_3 					 3
#define ITEM_EVENT_HALLOWEEN_4 					 4
#define ITEM_EVENT_FLOWER_20_11 					 5
#define ITEM_EVENT_XMAS_TREE_2014 					 10
#define ITEM_EVENT_BANH_CHUNG 					 11
#define ITEM_EVENT_BAO_LIXI_NORMAL 					 12
#define ITEM_EVENT_BAO_LIXI_SILVER 					 13
#define ITEM_EVENT_BAO_LIXI_GOLD 					 14
#define ITEM_EVENT_XMAS_2014_1 					 16 // cung
#define ITEM_EVENT_XMAS_2014_2 					 17 // ten
#define ITEM_EVENT_XMAS_2014_3 					 8
#define ITEM_EVENT_XMAS_2014_4 					 15
#define ITEM_EVENT_GLASS_ROSE 					 18
#define ITEM_EVENT_CANDLE 					 19

#define ITEM_EVENT_HALLOWEEN_1_PRICE 					 2 // cung
#define ITEM_EVENT_HALLOWEEN_2_PRICE 					 1 // ten
#define ITEM_EVENT_HALLOWEEN_3_PRICE 					 4

#define MATERIAL_LUCKY_LEAF_PURPLE_NUM 					 4
#define MATERIAL_LUCKY_LEAF_GREEN_NUM 					 4

#define SERVER_STATUS_PAUSE 					 0
#define SERVER_STATUS_READY 					 1
#define SERVER_STATUS_FORWARD 					 2

#define MAX_LEVEL 					 200
#define MAX_IBSHOP_PACK 					 299

#define NEW_COMER_ID 					 2575500

