



#define KEY_USER_COMMAND_ID 					 "command_id"
#define KEY_USER_REQUEST_STATUS 					 "request_status"
#define KEY_USER_ID 					 "user_id"
#define KEY_DEVICE_ID 					 "device_id"
#define KEY_DEVICE_NAME 					 "device_name"
#define KEY_DEVICE_FW 					 "device_fw"
#define KEY_DEVICE_IMEI 					 "device_imei"
#define KEY_EMAIL 					 "email"
#define KEY_PHONE_NUMBER 					 "phone_number"
#define KEY_USER_REQUEST_ID 					 "request_id"
#define KEY_USER_SESSION_ID 					 "session_id"
#define KEY_USER_NEW_SESSION_ID 					 "new_session_id"
#define KEY_USER_SESSION_EXPIRED_TIME 					 "session_expired_time"
#define KEY_REQUEST_STATUS 					 "request"
#define KEY_CLIENT_DATA 					 "client_data"
#define KEY_FACEBOOK_ID 					 "fb_id"
#define KEY_FACEBOOK_ACCESS_TOKEN 					 "fb_access_token"
#define KEY_FACEBOOK_LONG_LIVED_TOKEN 					 "fb_long_lived_token"
#define KEY_FACEBOOK_TOKEN_ISSUE_DATE 					 "fb_token_issue"
#define KEY_FACEBOOK_TOKEN_EXPIRE_DATE 					 "fb_token_expire"
#define KEY_FACEBOOK_NAME 					 "fb_name"
#define KEY_FACEBOOK_GENDER 					 "fb_gender"
#define KEY_FACEBOOK_BIRTHDAY 					 "fb_birthday"
#define KEY_FACEBOOK_LL_TOKEN 					 "fb_long_lived_token"
#define KEY_FACEBOOK_LIKE 					 "fb_like"
#define KEY_ZING_ID 					 "zing_id"
#define KEY_ZING_NAME 					 "zing_name"
#define KEY_ZING_DISPLAY_NAME 					 "zing_display_name"
#define KEY_ZING_ACCESS_TOKEN 					 "zing_access_token"
#define KEY_ZING_AVATAR 					 "zing_avatar"
#define KEY_ZALO_ID 					 "zalo_id"
#define KEY_ZALO_NAME 					 "zalo_name"
#define KEY_ZALO_DISPLAY_NAME 					 "zalo_display_name"
#define KEY_ZALO_ACCESS_TOKEN 					 "zalo_access_token"
#define KEY_ZALO_AVATAR 					 "zalo_avatar"
#define KEY_MONEY_REAL 					 "money_real"
#define KEY_MONEY_TOTAL 					 "money_total"
#define KEY_MONEY_BONUS 					 "money_bonus"
#define KEY_GARDEN_APPRAISAL 					 "garden_total_appraisal"
#define KEY_USER_IP 					 "user_ip"
#define KEY_USER_PHONE 					 "phone_number"
#define KEY_VERIFY_PHONE 					 "phone_verify_code"
#define KEY_FIRST_PLANT 					 "first_plant"
#define KEY_INVITE_FRIEND 					 "invite_friend"
#define KEY_USER_PHONE_LIST 					 "user_phone_list"
#define KEY_RECEIVED_GIFT_INSTALL_APP 					 "received_gift_install_app"
#define KEY_EVENT_MARKERS 					 "event_markers"
#define KEY_EVENT_GIFT_NUM 					 "event_gift_num"
#define KEY_EVENT_GIVE_FRIEND_GIFT_NUM 					 "event_give_friend_gift_num"
#define KEY_EVENT_CURRENT_TOTAL_NUM 					 "event_current_total_num"
#define KEY_NUM_GIFT_BOX_EVENT_RECEIVED 					 "num_gift_box_event_received"
#define KEY_NUM_GIFT_BOX_EVENT_HALLOWEEN 					 "_gift_box_received_event_halloween"
#define KEY_EVENT_ITEM_ID 					 "event_item_id"
#define KEY_EVENT_ITEM_LINK 					 "event_item_link"
#define KEY_EVENT_ITEM_MD5 					 "event_item_md5"
#define KEY_EVENT_ITEM_SPRITE_ID 					 "event_sprite_id"
#define KEY_EVENT_ITEM_SPRITE_CDN 					 "event_sprite_cdn"
#define KEY_ANDROID_ID 					 "android_id"
#define KEY_ADVERTISING_ID 					 "advertising_id"
#define KEY_BONUS_MARKER 					 "bonus_marker"

#define KEY_USER_INFOS 					 "user"
#define KEY_SEED_INFOS 					 "seed"
#define KEY_POT_INFOS 					 "pot"
#define KEY_PEST_INFOS 					 "pest"
#define KEY_WAREHOUSE_INFOS 					 "warehouse"

#define KEY_FLOORS 					 "floor_%d"
#define KEY_STOCKS 					 "stock_%d"
#define KEY_MACHINES 					 "machine_%d" // notice to client if we change this key
#define KEY_SLOTS 					 "slot_%d"
#define KEY_ORDER 					 "order"
#define KEY_GAME_CONSTANT 					 "gc_%d"
#define KEY_GAME_CONSTANT_MAX_ROW 					 "gc_max_row_%d"
#define KEY_IBSHOP 					 "ibshop"
#define KEY_PRIVATE_SHOP 					 "pshop"
#define KEY_FRIENDS 					 "friends"
#define KEY_FRIEND_PRIVATE_SHOP 					 "friend_pshop"
#define KEY_GIFT 					 "gift"
#define KEY_MERCHANT 					 "merchant"
#define KEY_NEWS_BOARD 					 "news_board"
#define KEY_ACHIEVEMENT 					 "achievement"
#define KEY_DAILY_GIFT 					 "dailygift"
#define KEY_TUTORIAL 					 "tutorial"
#define KEY_DROP_BONUS_ITEM 					 "dropbonusitem"
#define KEY_MACHINES_DURABILITY 					 "machine_durability_%d" // notice to client if we change this key
#define KEY_NPC_MACHINES_DURABILITY 					 "npc_machine_durability_%d"
#define KEY_NEW_DAY 					 "new_day"
#define KEY_MACHINES_REPAIR_LIMIT 					 "machine_repair_limit"
#define KEY_AIRSHIP 					 "airship"
#define KEY_FRIEND_AIRSHIP 					 "friend_airship"
#define KEY_TOM_KID 					 "tomkid"
#define KEY_FORTUNE 					 "fortune"
#define KEY_NOTIFY 					 "notify"
#define KEY_PRIVATE_INFO 					 "private_info"
#define KEY_ITEMS_EVENT 					 "items_event"
#define KEY_OFFER_MANAGER 					 "offer_manager"


#define KEY_USER_LEVEL 					 "user_level"
#define KEY_USER_EXP 					 "user_exp"
#define KEY_USER_EXP_LVL 					 "user_exp_lvl"
#define KEY_USER_GOLD 					 "user_gold"
#define KEY_USER_DIAMOND 					 "user_diamond"
#define KEY_USER_REPUTATION 					 "user_reputation"
#define KEY_USER_FLOOR 					 "user_floor"
#define KEY_USER_VIP_LEVEL 					 "user_vip_level"
#define KEY_USER_VIP_ACTIVE 					 "user_vip_active"
#define KEY_USER_VIP_TIME 					 "user_vip_time"
#define KEY_USER_NAME 					 "user_name"
#define KEY_USER_VIP 					 "user_vip"
#define KEY_USER_FRIEND_COUNT 					 "user_friend_count"
#define KEY_USER_LAST_LOGIN 					 "user_last_login"
#define KEY_USER_CURRENT_LOGIN 					 "user_current_login"
#define KEY_USER_LAST_LEVELUP 					 "user_last_levelup"
#define KEY_USER_BUG_APPEAR_RATIO 					 "user_bug_appear_ratio"

#define KEY_USER_ORDER_COUNT 					 "user_order_count"
#define KEY_USER_ORDER 					 "user_order_%d"
#define KEY_USER_ORDER_REWARD 					 "user_order_reward"

#define KEY_HAS_ORDER_EVENT 					 "has_order_event"

#define KEY_USER_REVENU_DATE_MAX 					 "user_revenu_date_max"
#define KEY_USER_REVENU_DATE 					 "user_revenu_date"
#define KEY_USER_REVENU_WEEK_MAX 					 "user_revenu_week_max"
#define KEY_USER_REVENU_WEEK 					 "user_revenu_week"
#define KEY_USER_REVENU_MONTH_MAX 					 "user_revenu_month_max"
#define KEY_USER_REVENU_MONTH 					 "user_revenu_month"

#define KEY_USER_ORDER_NUM_DATE_MAX 					 "user_order_num_date_max"
#define KEY_USER_ORDER_NUM_DATE 					 "user_order_num_date"
#define KEY_USER_USED_AMULET 					 "user_used_amulet"

#define KEY_USER_ACTION 					 "user_action"
#define KEY_USER_LIKED_LIST 					 "user_liked_list"
#define KEY_USER_LIKED_COUNT 					 "user_liked_count"
#define KEY_USER_LIKED 					 "user_liked"

#define KEY_USER_NEED_HELP_REPAIR_MACHINE					 "user_need_help_repair_machine"

#define KEY_NOTIFY_TITLE_TEXT 					 "notify_title_text"
#define KEY_NOTIFY_DESCRIPTION_TEXT 					 "notify_description_text"

#define KEY_UPDATE_RECOMMEND 					 "update_recommend"


#define FLOOR_NUM 					 "floor_num"
#define HARVEST_FIRST_FLOOR 					 "harvest_first_floor"
#define HARVEST_SECOND_FLOOR 					 "harvest_second_floor"
#define PLANT_FIRST_FLOOR 					 "plant_first_floor"
#define PLANT_SECOND_FLOOR 					 "plant_second_floor"
#define PUT_POT_FIRST_FLOOR 					 "put_pot_first_floor"
#define PUT_POT_SECOND_FLOOR 					 "put_pot_second_floor"


#define KEY_STOCK_ID 					 "stock_id"
#define KEY_STOCK_SILO 					 "stock_silo"
#define KEY_STOCK_BARN 					 "stock_barn"
#define KEY_STOCK_WAREHOUSE 					 "stock_warehouse"
#define KEY_STOCK_CAPACITY_MAX 					 "capacity_max"
#define KEY_STOCK_CAPACITY_CUR 					 "capacity_cur"

#define KEY_STOCK_PRODUCT_COUNT 					 "stock_product_count"
#define KEY_STOCK_PRODUCT_TYPE 					 "stock_product_type"
#define KEY_STOCK_PRODUCT_ID 					 "stock_product_id"
#define KEY_STOCK_PRODUCT_NUM 					 "stock_product_num"

#define KEY_STOCK_PRODUCT_INDEX 					 "stock_product_index"
#define KEY_STOCK_PRODUCT_EXP 					 "stock_product_exp"

#define KEY_STOCK_LEVEL 					 "stock_level"
#define KEY_STOCK_TOTAL_ITEM 					 "stock_total_item"
#define KEY_STOCK_ITEM_TYPE 					 "item_type_%d"
#define KEY_STOCK_ITEM_ID 					 "item_id_%d"
#define KEY_STOCK_ITEM_QUANTITY 					 "item_quantity_%d"


#define SLOT_PROPERTY_POT_ID 					 "pot_id"
#define SLOT_PROPERTY_SEED_ID 					 "seed_id"
#define SLOT_PROPERTY_GROWTIME 					 "growtime"
#define SLOT_PROPERTY_SOWTIME 					 "sowtime"
#define SLOT_PROPERTY_XP_RECEIVE 					 "xp"
#define SLOT_PROPERTY_PEST_ID 					 "pest"
#define KEY_SLOT_BONUS_EXP 					 "slot_bonus_exp"


#define KEY_SPECIAL_OFFER_ID 					 "key_offer_id"
#define KEY_SPECIAL_OFFER_LASTTIME 					 "key_offer_lasttime"
#define KEY_SPECIAL_OFFER_DURATION 					 "key_offer_duration"
#define KEY_SPECIAL_OFFER_OFFERRING 					 "key_offer_offerring"
#define KEY_SPECIAL_OFFER_ACCEPTED 					 "key_offer_accepted"
#define KEY_SPECIAL_OFFER_REJECTED 					 "key_offer_rejected"
#define KEY_SPECIAL_OFFER_TYPE 					 "key_offer_type"
#define KEY_SPECIAL_OFFER_REMAINING_TIME 					 "key_offer_remaining_time"
#define KEY_SPECIAL_OFFER_USER_GROUP 					 "key_offer_user_group"
#define KEY_SPECIAL_OFFER_DESCRIPTION 					 "key_offer_description"
#define KEY_SPECIAL_OFFER_NAME 					 "key_offer_name"
#define KEY_SPECIAL_OFFER_LINK_IMG 					 "key_offer_link_img"
#define KEY_SPECIAL_OFFER_MD5_IMG 					 "key_offer_md5_img"
#define KEY_SPECIAL_OFFER_BUTTON_LABEL 					 "key_offer_button_label"
#define KEY_SPECIAL_OFFER_WEB_LINK 					 "key_offer_web_link"
#define KEY_SPECIAL_OFFER_AVAILABLE_TIME 					 "key_offer_available_time"
#define KEY_SPECIAL_OFFER 					 "key_offer"
#define KEY_SPECIAL_OFFER_PACK_INFO 					 "key_offer_pack_info"
#define KEY_SPECIAL_OFFER_RECEIVE_TIME 					 "key_offer_receive_time"
#define KEY_SPECIAL_OFFER_USE_TIME 					 "key_offer_use_time"


#define KEY_MACHINE_ID 					 "machine_id"
#define KEY_MACHINE_FLOOR 					 "machine_floor"
#define KEY_MACHINE_LEVEL 					 "machine_level"
#define KEY_MACHINE_ACTIVE_TIME 					 "machine_active_time"
#define KEY_MACHINE_STATUS 					 "status"
#define KEY_MACHINE_DURABILITY_CUR 					 "durability_cur"
#define KEY_MACHINE_DURABILITY_MAX 					 "durability_max"
#define KEY_MACHINE_SLOT_MAX 					 "slot_max"
#define KEY_MACHINE_SLOT_CUR 					 "slot_cur"
#define KEY_MACHINE_START_TIME 					 "start_time"
#define KEY_MACHINE_PRODUCT_COUNT 					 "prod_count"

#define KEY_MACHINE_ITEM_DROP_LIST 					 "machine_item_drop_list"

#define KEY_MACHINE_SLOT_PRODUCT_ID 					 "slot_product_id"
#define KEY_MACHINE_SLOT_PRODUCT_TIME 					 "slot_product_time"

#define KEY_MACHINE_SLOT 					 "slot_%d"
#define KEY_MACHINE_PRODUCT 					 "prod_%d"

#define KEY_MACHINE_DECOR 					 "decor"

#define KEY_MACHINE_LOCK_DATA 					 "machine_lock_data"
#define KEY_REPAIR_FRIEND_MACHINE 					 "repair_friend_machine"
#define KEY_MACHINE_DURABILITY_REPAIRED 					 "machine_durability_repaired"
#define KEY_NPC_MACHINE_DAILY_RESET_TIME 					 "npc_machine_daily_reset_time"

#define KEY_REPUTATION_MAX_PER_DATE 					 "reputation_max_per_date"
#define KEY_REPUTATION_COLLECTED_PER_DATE					 "reputation_collected_per_date"
#define KEY_MACHINE_REPAIR_RESET_TIME 					 "machine_repair_reset_time"


#define KEY_PRODUCT_TYPE 					 "product_type"
#define KEY_PRODUCT_ID 					 "product_id"
#define KEY_MATERIAL_ID 					 "material_id"

#define KEY_PRODUCT_NUM 					 "product_num"
#define KEY_PRODUCT_EXP 					 "product_exp"


#define KEY_PLANT_ID 					 "plant_id"
#define KEY_PLANT_NAME 					 "plant_name"
#define KEY_PLANT_PRICE 					 "plant_price"
#define KEY_PLANT_START_TIME 					 "plant_start_time"
#define KEY_PLANT_GROW_TIME 					 "plant_grow_time"
#define KEY_PLANT_HARVEST_EXP 					 "plant_harvest_exp"
#define KEY_PLANT_ITEM_RECEIVE_RATIO 					 "plant_item_receive_ratio"
#define KEY_PLANT_DIAMON_SKIP_TIME 					 "plant_diamond_skip_time"
#define KEY_PLANT_DIAMON_BUY 					 "plant_diamond_buy"
#define KEY_PLANT_GOLD_SELL_DEFAULT 					 "plant_gold_sell_default"
#define KEY_PLANT_GOLD_SELL_MIN 					 "plant_gold_sell_min"
#define KEY_PLANT_GOLD_SELL_MAX 					 "plant_gold_sell_max"
#define KEY_PLANT_BUG_ID 					 "plant_bug_id"
#define KEY_PLANT_HAS_BUG 					 "plant_has_bug"
#define KEY_PLANT_BUG_APPEAR_RATIO 					 "plant_bug_appear_ratio"
#define KEY_PLANT_CURRENT_LEVEL 					 "plant_current_level"
#define KEY_PLANT_HARVEST_TO_LEVEL_UP 					 "plant_harvest_to_level_up"
#define KEY_PLANT_AT_FLOOR 					 "plant_at_floor"
#define KEY_PLANT_AT_SLOT 					 "plant_at_slot"
#define KEY_PLANT_LEVEL 					 "plant_level"
#define KEY_PLANT_COMBO_ID 					 "plant_combo_id"
#define KEY_PLANT_COMBO_EXP_BONUS 					 "plant_combo_exp_bonus"
#define KEY_PLANT_FERTILIZER_ID 					 "plant_fertilizer_id"
#define KEY_PLANT_FERTILIZER_REDUCE_TIME 					 "plant_fertilizer_reduce_time"


#define KEY_POT_ID 					 "pot_id"
#define KEY_POT_NAME 					 "pot_name"
#define KEY_POT_PRICE 					 "pot_price"
#define KEY_POT_UNLOCK_EXP 					 "pot_unlock_exp"
#define KEY_POT_EXP_INCREASE 					 "pot_exp_increase"
#define KEY_POT_TIME_DECREASE 					 "pot_time_decrease"
#define KEY_POT_GOLD_UPGRADE 					 "pot_gold_upgrade"
#define KEY_POT_PEARL_ID_NUM 					 "pot_pearl_id_num"
#define KEY_POT_UPGRADE_RATIO 					 "pot_upgrade_ratio"
#define KEY_POT_GOLD_DEFAULT 					 "pot_gold_default"
#define KEY_POT_GOLD_MIN 					 "pot_gold_min"
#define KEY_POT_GOLD_MAX 					 "pot_gold_max"
#define KEY_POT_AT_FLOOR 					 "pot_at_floor"
#define KEY_POT_AT_SLOT 					 "pot_at_slot"
#define KEY_POT_LEVEL 					 "pot_level"


#define KEY_DECOR_ID 					 "decor_id"
#define KEY_DECOR_AT_FLOOR 					 "decor_at_floor"
#define KEY_DECOR_AT_SLOT 					 "decor_at_slot"


#define KEY_SLOT_INDEX 					 "slot_id"
#define KEY_SLOT_HARVEST_EXP 					 "slot_harvest_exp"


#define KEY_FLOOR_INDEX 					 "floor_id"
#define KEY_TOTAL_FLOOR_CHANGED 					 "total_floor_changed"
#define KEY_FLOOR_COMBO_ID 					 "floor_combo_id"


#define KEY_VERSION_PLATFORM 					 "version_platform"
#define KEY_VERSION_RESOLUTION 					 "version_resolution"
#define KEY_VERSION_NUMBER 					 "version_number"
#define KEY_VERSION_LINK 					 "version_link"
#define KEY_VERSION_UPDATE 					 "version_update"
#define KEY_VERSION_FORCE_UPDATE 					 "version_force_update"
#define KEY_INSTALL_REFERENCE 					 "install_reference"


#define KEY_ORDER_TYPE 					 "order_type"
#define KEY_ORDER_FREE_DELIVERED_NUM 					 "order_free_delivered_num"
#define KEY_ORDER_PAID_DELIVERED_NUM 					 "order_paid_delivered_num"
#define KEY_ORDER_DAILY_FREE_MAX 					 "order_daily_free_max"
#define KEY_ORDER_DAILY_PAID_MAX 					 "order_daily_paid_max"
#define KEY_TOTAL_DELIVERED_NUM 					 "total_order_daily_per_date"
#define KEY_ORDER_DAILY_RESET_TIME 					 "order_daily_reset_time"
#define KEY_DAILY_ORDER_LETTER_SELECTED 					 "order_daily_letter_selected"

#define KEY_ORDER_DELIVERY_TIME 					 "order_delivery_time"

#define KEY_ORDER_REWARD_GOLD_RATIO_FROM_POT 					 "order_reward_gold_ratio_from_pot"
#define KEY_ORDER_REWARD_EXP_RATIO_FROM_POT 					 "order_reward_exp_ratio_from_pot"
#define KEY_ORDER_REWARD_GOLD_RATIO_FROM_MACHINE 					 "order_reward_gold_ratio_from_machine"
#define KEY_ORDER_REWARD_GOLD_RATIO_FROM_EVENT 					 "order_reward_gold_ratio_from_event"
#define KEY_ORDER_REWARD_EXP_RATIO_FROM_MACHINE 					 "order_reward_exp_ratio_from_machine"
#define KEY_ORDER_REWARD_EXP_RATIO_FROM_EVENT 					 "order_reward_exp_ratio_from_event"
#define KEY_ORDER_SKIPPING 					 "order_skipping"

#define KEY_ORDER_REWARD_GOLD 					 "order_reward_gold"
#define KEY_ORDER_REWARD_GOLD_BONUS 					 "order_reward_gold_bonus"

#define KEY_ORDER_REWARD_EXP 					 "order_reward_exp"
#define KEY_ORDER_REWARD_EXP_BONUS 					 "order_reward_exp_bonus"

#define KEY_ORDER_REWARD_DIAMOND 					 "order_reward_diamond"
#define KEY_ORDER_ITEM_COUNT 					 "order_reward_item_count"
#define KEY_ORDER_PRODUCT_COUNT 					 "order_reward_prod_count"
#define KEY_ORDER_NPC 					 "order_npc"
#define KEY_ORDER_NEW_WAIT_TIME 					 "order_new_wait_time"

#define KEY_ORDER_RECEIVE 					 "order_receive"
#define KEY_ORDER_RECEIVE_DIAMOND 					 "order_receive_diamond"
#define KEY_ORDER_LETTER_SELECT_INDEX 					 "order_letter_select_index"
#define KEY_ORDER_LETTER_SELECT_VALUE 					 "order_letter_select_value"

#define KEY_ORDER_LETTERS_ENABLE 					 "order_letters_enable_%d"
#define KEY_ORDER_LETTERS_VALUE 					 "order_letters_value_%d"

#define KEY_ORDER_INDEX 					 "order_index"
#define KEY_ORDER_REWARD 					 "order_reward"
#define KEY_ORDER_ITEM 					 "item_%d"
#define KEY_ORDER_PRODUCT 					 "prod_%d"

#define KEY_ORDER_LETTER_INDEX 					 "order_letter_index"
#define KEY_LETTER_RESELECT_DIAMOND 					 "letter_reselect_diamond"


#define KEY_IBS_PACKAGE_INDEX 					 "ibs_pack_idx"
#define KEY_IBS_PACKAGE_ID 					 "ibs_package_%d"
#define KEY_IBS_PACKAGE_TYPE 					 "ibs_package_type"
#define KEY_IBS_PACKAGE_NAME 					 "ibs_package_name"
#define KEY_IBS_PACKAGE_DES 					 "ibs_package_des"
#define KEY_IBS_PACKAGE_NAME_EN 					 "ibs_package_name_en"
#define KEY_IBS_PACKAGE_DES_EN 					 "ibs_package_des_en"
#define KEY_IBS_PACKAGE_NAME_SC 					 "ibs_package_name_sc"
#define KEY_IBS_PACKAGE_DES_SC 					 "ibs_package_des_sc"
#define KEY_IBS_PACKAGE_NAME_TC 					 "ibs_package_name_tc"
#define KEY_IBS_PACKAGE_DES_TC 					 "ibs_package_des_tc"
#define KEY_IBS_PACKAGE_CASH_ID 					 "ibs_package_cash_id"
#define KEY_IBS_ITEM_TYPE 					 "ibs_item_type"
#define KEY_IBS_ITEM_ID 					 "ibs_item_id"
#define KEY_IBS_ITEM_QUANTIFY 					 "ibs_item_quantity"
#define KEY_IBS_IS_ACTIVE 					 "ibs_is_active"
#define KEY_IBS_IS_NEW 					 "ibs_is_new"
#define KEY_IBS_IS_HOT 					 "ibs_is_hot"
#define KEY_IBS_IS_SALE_OFF 					 "ibs_is_sale_off"
#define KEY_IBS_SALE_OFF_PERCENT 					 "ibs_sale_off_percent"
#define KEY_IBS_HAS_PROMOTION 					 "ibs_has_promotion"
#define KEY_IBS_GIFT_WHEN_BUY 					 "ibs_gift_when_buy"
#define KEY_IBS_REQUIRED_GOLD 					 "ibs_required_gold"
#define KEY_IBS_REQUIRED_DIAMOND 					 "ibs_required_diamond"
#define KEY_IBS_REQUIRED_REPUTATION 					 "ibs_required_reputation"
#define KEY_IBS_HAS_TIME_LIMIT 					 "ibs_sale_limit_time"
#define KEY_IBS_SALE_DURATION 					 "ibs_sale_duration"
#define KEY_IBS_HAS_SALE_LIMIT 					 "ibs_sale_limit_quantity"
#define KEY_IBS_SALE_TOTAL_QUANTITY 					 "ibs_sale_total_quantity"
#define KEY_IBS_UNLOCK_LEVEL 					 "ibs_unlock_level"
#define KEY_IBS_REMAINING_QUANTITY 					 "ibs_remaining_quantity"
#define KEY_IBS_MAX_PACKAGE_NUMBER 					 "ibs_max_package_number"
#define KEY_IBS_DISPLAY_IDX 					 "ibs_display_idx"


#define KEY_PS_SLOT 					 "ps_slot_%d"
#define KEY_PS_CURRENT_SLOT_NUMBER 					 "ps_current_slot_number"
#define KEY_PS_ADVERTISE_AVAILABLE_TIME 					 "ps_advertise_available_time"
#define KEY_PS_SLOT_ID 					 "ps_slot_id"
#define KEY_PS_SLOT_STATUS 					 "ps_slot_status"
#define KEY_PS_NEXT_REQUIRED_FRIEND 					 "ps_slot_next_required_friend"
#define KEY_PS_NEXT_REQUIRED_DIAMOND 					 "ps_slot_next_required_diamond"

#define KEY_PS_START_HIRE_DATE 					 "ps_start_hire"
#define KEY_PS_END_HIRE_DATE 					 "ps_end_hire"
#define KEY_PS_ITEM 					 "ps_item"
#define KEY_PS_ITEM_TYPE 					 "ps_item_type"
#define KEY_PS_ITEM_ID 					 "ps_item_id"
#define KEY_PS_ITEM_NUMBER 					 "ps_item_number"
#define KEY_PS_ITEM_START_SELL_DATE 					 "ps_item_start_date"
#define KEY_PS_ITEM_END_SELL_DATE 					 "ps_item_end_date"
#define KEY_PS_ITEM_STATUS 					 "ps_item_status"
#define KEY_PS_ITEM_MONEY_TYPE 					 "ps_item_money_type"
#define KEY_PS_ITEM_PRICE 					 "ps_item_price"
#define KEY_PS_ITEM_CANCEL_PRICE 					 "ps_item_cancel_price"
#define KEY_PS_ITEM_ADVERTISE 					 "ps_item_advertise"
#define KEY_PS_ITEM_BUYER_ID 					 "ps_item_buyer_id"
#define KEY_PS_ITEM_END_ADVERTISE_TIME 					 "ps_item_end_advertise_time"

#define KEY_PS_LOCK_DATA 					 "ps_lock_data"
#define KEY_PS_VIEWER 					 "ps_viewer"


#define KEY_GIFT_LIST 					 "gift_%d"
#define KEY_GIFT_ID 					 "gift_id"
#define KEY_GIFT_NAME 					 "gift_name"
#define KEY_GIFT_DESCRIPTION 					 "gift_description"
#define KEY_GIFT_ITEM_LIST 					 "gift_item_list"
#define KEY_GIFT_AVAILABLE 					 "gift_available"
#define KEY_GIFT_INFO 					 "gift_info"

#define KEY_DAILY_GIFTS_RECEIVED 					 "daily_gifts_received"
#define KEY_DAILY_GIFTS 					 "daily_gifts"
#define KEY_DAILY_GIFTS_TIME_RANGE 					 "daily_gifts_time_range"
#define KEY_DAILY_GIFTS_TIME_RANGE_S 					 "daily_gifts_time_range_s"


#define KEY_GIFT_CODE_ID 					 "gift_code_id"
#define KEY_GIFT_CODE_SERVER_CODE 					 "gift_code_server_code"
#define KEY_GIFT_CODE_CLIENT_CODE 					 "gift_code_client_code"
#define KEY_GIFT_CODE_GIFT_CODE 					 "gift_code_gift_code"
#define KEY_GIFT_CODE_NAME 					 "gift_code_name"
#define KEY_GIFT_CODE_DESCRIPTION 					 "gift_code_description"
#define KEY_GIFT_CODE_GIFT 					 "gift_code_gift"
#define KEY_GIFT_CODE_START_TIME 					 "gift_code_start_time"
#define KEY_GIFT_CODE_END_TIME 					 "gift_code_end_time"
#define KEY_GIFT_CODE_USE_TIME 					 "gift_code_use_time"
#define KEY_GIFT_CODE_RECEIVED 					 "gift_code_received"

#define KEY_GIFT_CODE_ENTER 					 "gift_code_enter"
#define KEY_GIFT_CODE_ENTER_MAX 					 "gift_code_enter_max"
#define KEY_GIFT_CODE_ENTER_NUM 					 "gift_code_enter_num"
#define KEY_GIFT_CODE_TOTAL 					 "gift_code_total"
#define KEY_GIFT_TYPE_TOTAL 					 "gift_type_total"
#define KEY_GIFT_TYPE 					 "gift_type"

#define KEY_GIFT_TYPE_ID 					 "gift_type_id"
#define KEY_GIFT_TYPE_USE_TIME 					 "gift_type_use_time"


#define KEY_USER_DAILY_GIFT_RECEIVE_TIME 					 "user_daily_gift_receive_time"
#define KEY_USER_DAILY_GIFT_GIFTS 					 "user_daily_gift_gifts"


#define KEY_FRIEND_COUNT 					 "friend_count"
#define KEY_FRIEND_LIST 					 "friend_list"
#define KEY_FRIEND_INDEX 					 "friend_%d"
#define KEY_FRIEND_NEED_HELP 					 "friend_need_help_%d"
#define KEY_FRIEND_LIST_STEP 					 "friend_list_step"//for loadind step friend list
#define KEY_FRIEND_LIST_STEP_MAX 					 "friend_list_step_max"//for loadind step friend list

#define KEY_FRIEND_LIST_TOKEN 					 "friend_list_token"
#define KEY_FRIEND_LIST_INFO 					 "friend_list_info"
#define KEY_FRIEND_FB_LIST_INFO 					 "friend_fb_list_info"
#define KEY_FRIEND_ZING_LIST_INFO 					 "friend_zing_list_info"
#define KEY_FRIEND_ZALO_LIST_INFO 					 "friend_zalo_list_info"
#define KEY_PREVIOUS_FRIEND_DEVICE_ID 					 "previous_friend_device_id"
#define KEY_FRIEND_BUG 					 "friend_bug"
#define KEY_FRIEND_BUG_TYPE 					 "friend_bug_type"
#define KEY_FRIEND_BUG_ID 					 "friend_bug_id"
#define KEY_FRIEND_BUG_POS_X 					 "friend_bug_pos_x"
#define KEY_FRIEND_BUG_POS_Y 					 "friend_bug_pos_y"


#define KEY_SERVER_TIME_INT 					 "second"
#define KEY_SERVER_VERSION 					 "server_version"

#define KEY_FRIEND_INFOS 					 "friend"
#define KEY_FRIEND_ID 					 "friend_id"
#define KEY_FRIEND_DEVICE_ID 					 "friend_device_id"

#define KEY_RESET_ACCOUNT 					 "reset_account"
#define KEY_LOAD_FRIEND_SHOP 					 "load_friend_shop"


#define KEY_ACHIEVEMENT_ID 					 "achievement_id"
#define KEY_ACHIEVEMENT_LEVEL 					 "achievement_level"
#define KEY_ACHIEVEMENT_ITEM_CUR 					 "achievement_item_cur"
#define KEY_ACHIEVEMENT_ITEM_MAX 					 "achievement_item_max"
#define KEY_ACHIEVEMENT_REWARD_COUNT 					 "achievement_reward_count"
#define KEY_ACHIEVEMENT_REWARD 					 "achievement_reward_%d"
#define KEY_ACHIEVEMENT_TOTAL 					 "achievement_total"
#define KEY_ACHIEVEMENT_INDEX 					 "achievement_index_%d"
#define KEY_ACHIEVEMENT_RECEIVED_GIFT 					 "achievement_received_gift_%d"
#define KEY_ACHIEVEMENT_RECEIVED_GIFT_SPECIAL 					 "achievement_received_gift_special"
#define KEY_ACHIEVEMENT_GIFT_INDEX 					 "achievement_gift_index"


#define KEY_PROD_TYPE 					 "prod_type"
#define KEY_PROD_ID 					 "prod_id"
#define KEY_PROD_NUM 					 "prod_num"


#define KEY_TUTORIAL_ENABLE 					 "tutorial_enable"
#define KEY_TUTORIAL_STEP 					 "tutorial_step"
#define KEY_TUTORIAL_FIRST_PLANT_HAS_BUG 					 "tutorial_first_plant_has_bug"
#define KEY_TUTORIAL_STARTED 					 "tutorial_started_%d"
#define KEY_TUTORIAL_FINISHED 					 "tutorial_finished_%d"
#define KEY_TUTORIAL_EXP 					 "tutorial_exp_%d"

#define KEY_TUTORIAL_EXP_REWARD 					 "tutorial_exp_reward"
#define KEY_TUTORIAL_START 					 "tutorial_start"
#define KEY_TUTORIAL_FINISH 					 "tutorial_finish"


#define KEY_OWL 					 "owl"

#define KEY_OWL_POWER_LIMIT 					 "owl_limit"
#define KEY_OWL_POWER_CURRENT 					 "owl_limit_current"
#define KEY_OWL_SLOT_MAX 					 "owl_slot_max"
#define KEY_OWL_SLOT_CUR 					 "owl_slot_cur"
#define KEY_OWL_SLOT 					 "owl_slot_%d"

#define KEY_OWL_FOOD_ID 					 "owl_food_id"
#define KEY_OWL_DIGEST_TIME 					 "owl_digest_time"

#define KEY_OWL_TOTAL_SLOT 					 "owl_total_slot"
#define KEY_OWL_DIAMOND_UNLOCK_NEXT_SLOT					 "owl_diamond_unlock_next_slot"
#define KEY_OWL_GOLD_UNLOCK_NEXT_SLOT 					 "owl_gold_unlock_next_slot"


#define KEY_NPC_BUY_ITEM_INFOS 					 "npc_buy_item_infos"

#define KEY_NPC_BUY_ITEM_TIMER 					 "npc_buy_item_timer"
#define KEY_NPC_BUY_ITEM_ID 					 "npc_buy_item_id"
#define KEY_NPC_BUY_ITEM_NUM 					 "npc_buy_item_num"
#define KEY_NPC_BUY_ITEM_PRICE 					 "npc_buy_item_price"


#define KEY_EVENT 					 "event"
#define KEY_EVENT_MAIN_OBJECT 					 "event_main_object"

#define KEY_EVENT_ID 					 "event_id"
#define KEY_EVENT_NAME 					 "event_name"
#define KEY_EVENT_START_TIME 					 "event_start_time"
#define KEY_EVENT_END_TIME 					 "event_end_time"
#define KEY_EVENT_START_TIME_BEFORE 					 "event_start_time_before"
#define KEY_EVENT_END_TIME_BEFORE 					 "event_end_time_before"
#define KEY_EVENT_ITEM_PRICE 					 "event_item_price"

#define KEY_EVENT_MO_ID 					 "event_mo_id"
#define KEY_EVENT_MO_POS 					 "event_mo_pos"
#define KEY_EVENT_MO_HIT_COUNT 					 "event_mo_hit_count"
#define KEY_EVENT_MO_HIT_CURRENT 					 "event_mo_hit_current"
#define KEY_EVENT_MO_FIRST_ACTION 					 "event_mo_first_action"
#define KEY_EVENT_MO_LAST_ACTION 					 "event_mo_last_action"
#define KEY_EVENT_MO_HIT_ACTION 					 "event_mo_hit_action"
#define KEY_EVENT_MO_SPRITE_ID 					 "event_mo_sprite_id"

#define KEY_EVENT_MI_ID 					 "event_mi_id"


#define KEY_AIRSHIP_ID 					 "airship_id"
#define KEY_AIRSHIP_REQUIRE_LEVEL 					 "airship_require_level"
#define KEY_AIRSHIP_REQUIRE_ITEMS 					 "airship_require_items"
#define KEY_AIRSHIP_UNLOCK_DURATION 					 "airship_unlock_duration"
#define KEY_AIRSHIP_STAY_DURATION 					 "airship_stay_duration"
#define KEY_AIRSHIP_LEAVE_DURATION 					 "airship_leave_duration"
#define KEY_AIRSHIP_MIN_POINT 					 "airship_min_point"
#define KEY_AIRSHIP_MAX_POINT 					 "airship_max_point"
#define KEY_AIRSHIP_HELP_TIME 					 "airship_help_time"
#define KEY_AIRSHIP_MIN_BONUS_GOLD 					 "airship_min_bonus_gold"
#define KEY_AIRSHIP_MAX_BONUS_GOLD 					 "airship_max_bonus_gold"
#define KEY_AIRSHIP_MIN_BONUS_EXP 					 "airship_min_bonus_exp"
#define KEY_AIRSHIP_MAX_BONUS_EXP 					 "airship_max_bonus_exp"
#define KEY_AIRSHIP_POINT_REDUCE 					 "airship_point_reduce"
#define KEY_AIRSHIP_CARGO_COUNT 					 "airship_cargo_count"
#define KEY_AIRSHIP_CARGO 					 "airship_cargo_%d"
#define KEY_AIRSHIP_UNLOCK_TIME 					 "airship_unlock_time"
#define KEY_AIRSHIP_UNLOCK_DIAMOND 					 "airship_unlock_diamond"
#define KEY_AIRSHIP_STATUS 					 "airship_status"
#define KEY_AIRSHIP_DIAMOND_PRICE 					 "airship_diamond_price"
#define KEY_AIRSHIP_LAST_LANDING_TIME 					 "airship_last_landing_time"
#define KEY_AIRSHIP_NEXT_LANDING_TIME 					 "airship_next_landing_time"
#define KEY_AIRSHIP_DEPART_TIME 					 "airship_depart_time"
#define KEY_AIRSHIP_GOLD 					 "airship_gold"
#define KEY_AIRSHIP_EXP 					 "airship_exp"
#define KEY_AIRSHIP_POINT 					 "airship_point"
#define KEY_AIRSHIP_REPUTATION 					 "airship_reputation"
#define KEY_AIRSHIP_PREVIEW_INFO 					 "airship_preview_info"
#define KEY_AIRSHIP_SKIP_DEPART_TIME_PRICE 					 "airship_skip_depart_time_price"
#define KEY_AIRSHIP_REPUTATION_REDUCE_PER_HOUR 					 "airship_reputation_reduce_per_hour"
#define KEY_AIRSHIP_CURRENT_NUM 					 "airship_current_num"
#define KEY_AIRSHIP_MAX_NUM_PER_DAY 					 "airship_max_num_per_day"
#define KEY_AIRSHIP_SECONDS_REDUCE_REPUTATION 					 "airship_seconds_reduce_reputation"
#define KEY_AIRSHIP_SECONDS_PER_DIAMOND 					 "airship_seconds_per_diamond"
#define KEY_AIRSHIP_LOCKER 					 "airship_locker"


#define KEY_CARGO_ID 					 "cargo_id"
#define KEY_CARGO_ITEM_TYPE 					 "cargo_item_type"
#define KEY_CARGO_ITEM_ID 					 "cargo_item_id"
#define KEY_CARGO_ITEM_NUM 					 "cargo_item_num"
#define KEY_CARGO_EXP 					 "cargo_exp"
#define KEY_CARGO_GOLD 					 "cargo_gold"
#define KEY_CARGO_REPUTATION 					 "cargo_reputation"
#define KEY_CARGO_IS_FINISHED 					 "cargo_is_finished"
#define KEY_CARGO_ASK_FOR_HELP 					 "cargo_ask_for_help"
#define KEY_CARGO_DIAMOND_PRICE 					 "cargo_diamond_price"
#define KEY_CARGO_FRIEND_ID 					 "cargo_friend_id"


#define KEY_TOM_KID_STATUS 					 "tomkid_status"
#define KEY_TOM_KID_FIRST_USED 					 "tomkid_first_used"
#define KEY_TOM_KID_LAST_HIRE_TIME 					 "tomkid_last_hire_time"
#define KEY_TOM_KID_EXPIRE_HIRE_TIME 					 "tomkid_expire_hire_time"
#define KEY_TOM_KID_PRICE_HIRE_1_DAY 					 "tomkid_price_1_day"
#define KEY_TOM_KID_PRICE_HIRE_3_DAY 					 "tomkid_price_3_day"
#define KEY_TOM_KID_PRICE_HIRE_7_DAY 					 "tomkid_price_7_day"
#define KEY_TOM_KID_LONG_REST_DURATION 					 "tomkid_long_rest"
#define KEY_TOM_KID_SHORT_REST_DURATION 					 "tomkid_short_rest"
#define KEY_TOM_KID_SUGGEST_ITEM 					 "tomkid_suggest_item_%d"
#define KEY_TOM_KID_SUGGEST_ITEM_ID 					 "tomkid_suggest_item_id"
#define KEY_TOM_KID_ITEM_TYPE 					 "tomkid_item_type"
#define KEY_TOM_KID_ITEM_ID 					 "tomkid_item_id"
#define KEY_TOM_KID_ITEM_NUM 					 "tomkid_item_num"
#define KEY_TOM_KID_ITEM_GOLD_PRICE 					 "tomkid_item_gold_price"
#define KEY_TOM_KID_SUGGEST_COUNT 					 "tomkid_suggest_count"
#define KEY_TOM_KID_LAST_WORKING_TIME 					 "tomkid_last_working_time"
#define KEY_TOM_KID_NEXT_WORKING_TIME 					 "tomkid_next_working_time"
#define KEY_TOM_KID_HIRE_PACK 					 "tomkid_hire_pack"
#define KEY_TOM_KID_UNLOCK_LEVEL 					 "tomkid_unlock_level"



#define KEY_MOVE_POT_SRC_FLOOR_INDEX 					 "floor_index_src"
#define KEY_MOVE_POT_SRC_SLOT_INDEX 					 "slot_index_src"
#define KEY_MOVE_POT_DES_FLOOR_INDEX 					 "floor_index_des"
#define KEY_MOVE_POT_DES_SLOT_INDEX 					 "slot_index_des"

#define KEY_LUCKY_LEAF 					 "lucky_leaf_id"
#define KEY_AMULET 					 "amulet"

#define KEY_PUT_POT 					 "put_pot_%d"
#define KEY_PLANT_FLOWER 					 "plant_%d"
#define KEY_HARVEST 					 "harvest_%d"
#define KEY_CATCH_BUG 					 "catch_bug_%d"
#define KEY_PLANT_INSTANT_GROW 					 "instant_grow_%d"


#define KEY_PLACE_DECOR 					 "place_decor_%d"


#define KEY_USE_FERTILIZER 					 "use_fertilizer_%d"


#define KEY_SHARE_CONTENT 					 "social_share_content"

#define KEY_EXP_RECEIVE 					 "exp_receive"
#define KEY_EXP_RECEIVE_SLOT 					 "exp_receive_slot_%d"
#define KEY_BUG_COUNT 					 "bug_count"
#define KEY_NEXT_TIME_BUG_APPEAR 					 "next_time_bug_appear"
#define KEY_BUG_POOL 					 "bug_pool"


#define KEY_MAX_ROW 					 "max_row"
#define KEY_MAX_COL 					 "max_column"


#define FRIEND_DEVICE_ID 					 "friend_device_id"
#define FRIEND_USER_ID 					 "friend_user_id"
#define FRIEND_FB_ID 					 "friend_fb_id"
#define KEY_FACEBOOK_FRIEND_PARAM 					 "fb_friend_param"
#define KEY_ZING_FRIEND_PARAM 					 "zing_friend_param"
#define KEY_RECEIVED_GIFT_INVITE_FRIEND 					 "received_gift_invite_%d"
#define KEY_GIFT_INVITE_FRIEND_INDEX 					 "gift_invite_friend_index"
#define KEY_NUM_FRIEND_INVITED 					 "num_friend_invited"


#define REQUESTED_USER_ID 					 "requested_user_id"
#define REQUESTED_SESSION_ID 					 "requested_session_id"


#define KEY_ADS_LIMIT_TIME 					 "ads_limit_time"
#define KEY_ADS_NUM 					 "ads_num"
#define KEY_ADS_USER_ID 					 "ads_user_id_%d"
#define KEY_ADS_USER_ITEM 					 "ads_user_item_%d"

#define KEY_ADS_USER_INFO 					 "ads_user_info_%d"

#define KEY_ADS_KEY 					 "ads_key"
#define KEY_ADS_ITEM 					 "ads_item"
#define KEY_ADS_LIST 					 "ads_list"


#define KEY_SERVER_ADDRESS 					 "s_address"
#define KEY_SERVER_PORT 					 "s_port"
#define KEY_SERVER_LIST 					 "server_list"
#define KEY_TOTAL_SERVER 					 "total_server_number"
#define KEY_SERVER_INDEX 					 "server_%d"


#define KEY_GOLD_USED 					 "gold_used"
#define KEY_EXP_USED 					 "exp_used"
#define KEY_DIAMOND_USED 					 "diamond_used"
#define KEY_REPUTATION_USED 					 "reputation_used"
#define KEY_ITEM_NUM_USED 					 "item_num_used"


#define KEY_GM_ID 					 "gm_id"
#define KEY_GM_TOKEN 					 "gm_token"
#define KEY_GM_COMMAND 					 "gm_command"
#define KEY_GM_SESSION 					 "gm_session"
#define KEY_GM_LOGIN_TIME 					 "gm_login_time"
#define KEY_BROADCAST_CONTENT 					 "broadcast_content"
#define KEY_BROADCAST_CONTENT_LIST 					 "broadcast_content_list"
#define KEY_BROADCAST_REPEAT_TIMES 					 "broadcast_repeat_times"
#define KEY_BROADCAST_DURATION 					 "broadcast_duration"
#define KEY_CLOUD_MESSAGE_CONTENT 					 "cloud_content"
#define KEY_CLOUD_MESSAGE_REG_LIST 					 "cloud_reg_list"
#define KEY_CLOUD_MESSAGE_OS 					 "cloud_os"


#define KEY_PAYMENT_CARD_SERIALNO 					 "card_serialno"
#define KEY_PAYMENT_CARD_PIN 					 "card_pin"
#define KEY_PAYMENT_CARD_TYPE 					 "card_type"
#define KEY_PAYMENT_RESULT 					 "transaction_result"
#define KEY_PAYMENT_ENABLE 					 "payment_enable"
#define KEY_PAYMENT_APPSTORE_ENABLE 					 "payment_appstore_enable"
#define KEY_PAYMENT_USE_FIRST_PAY 					 "payment_first_pay"

#define KEY_USE_WIFI 					 "use_wifi"
#define KEY_CARRIER_NAME 					 "carrier_name"
#define KEY_DISTRIBUTOR 					 "distributor"
#define KEY_FLURRY 					 "flurry"
#define KEY_EMAIL_SUPPORT 					 "email_support"
#define KEY_PHONE_SUPPORT 					 "phone_support"
#define KEY_ONLINE_SUPPORT 					 "online_support"


#define NPC_NAME 					 "NPC_JACK"

#define ONLINE 					 "online"
#define BAN 					 "ban"

#define KEY_LAST_PAY_TIME 					 "last_pay"
#define KEY_FIRST_PAY_CAMPAIGN_STATUS 					 "firstpay_status"
#define KEY_TOTAL_PAID 					 "total_paid"

#define KEY_EVENT_NOTIFY_ENABLE 					 "key_event_notify_enable"
#define KEY_EVENT_NOTIFY_TYPE 					 "key_event_notify_type"
#define KEY_EVENT_NOTIFY_NAME 					 "key_event_notify_name"
#define KEY_EVENT_NOTIFY_DETAILS 					 "key_event_notify_details"
#define KEY_EVENT_NOTIFY_PLATFORM 					 "key_event_notify_platform"
#define KEY_EVENT_NOTIFY_IMG_SMALL 					 "key_event_notify_img_small"
#define KEY_EVENT_NOTIFY_IMG_LARGE 					 "key_event_notify_img_large"
#define KEY_EVENT_NOTIFY_IMG_SMALL_MD5 					 "key_event_notify_img_small_md5"
#define KEY_EVENT_NOTIFY_IMG_LARGE_MD5 					 "key_event_notify_img_large_md5"


#define KEY_ATM_GAME_ID 					 "key_game_id"
#define KEY_ATM_GAME_TOKEN 					 "key_atm_token"
#define KEY_ATM_ADD_INFO 					 "key_atm_add_info"
#define KEY_ATM_TARGET_URL 					 "key_atm_target_url"
#define KEY_ATM_IMAGE 					 "key_atm_image"
#define KEY_ATM_MD5 					 "key_atm_md5"
#define KEY_ATM_HAS_PROMOTION 					 "key_atm_has_promotion"


#define KEY_MERCHANT_LIST 					 "merchant_%d"
#define KEY_MERCHANT_ID 					 "merchant_id"


#define KEY_FEED 					 "key_feed"
#define KEY_FEED_TITLE 					 "key_feed_title"
#define KEY_FEED_DESCRIPTION 					 "key_feed_description"
#define KEY_FEED_LINK 					 "key_feed_link"
#define KEY_FEED_IMG_LINK 					 "key_feed_img_link"
#define KEY_FEED_CAPTION 					 "key_feed_caption"

#define FEED_TYPE_POT 					 "p"
#define FEED_TYPE_MACHINE 					 "m"
#define FEED_TYPE_LEVEL 					 "l"
#define FEED_TYPE_FLOOR 					 "f"

#define FEED_ACTION_UPGRADE 					 "0"
#define FEED_ACTION_UPGRADE_BLESSING 					 "1" // nang cap chau vuot cap
#define FEED_ACTION_UNLOCK_MACHINE 					 "2"

#define FEED_ACTION_LEVEL_UP 					 "0"
#define FEED_ACTION_OVERTAKE_FRIEND 					 "1" // vuot level ban be

#define FEED_ACTION_OPEN_FLOOR 					 "0"


#define KEY_GCM_ID 					 "gcm_id"
#define KEY_REGISTERED_GCM_ANDROID 					 "gcm_has_reg_id_android"
#define KEY_REGISTER_GCM_IOS 					 "gcm_has_reg_id_ios"

#define FIRST_PAY_ADS_LINK 					 "http://sgmb.static.g6.zing.vn/ads/firstpay.png"
#define FIRST_PAY_ADS_LINK_IOS 					 "http://sgmb.static.g6.zing.vn/ads/firstpay_ios.png"
#define FIRST_PAY_ADS_LINK_SD 					 "http://sgmb.static.g6.zing.vn/ads/firstpay_sd.png"
#define KEY_FIRST_PAY_ADS_LINK 					 "key_first_pay_link"
#define KEY_FIRST_PAY_ADS_MD5 					 "key_first_pay_md5"
#define FIRST_PAY_ADS_MD5 					 "1f2e5bc377b745954addacf0f237fb54"
#define FIRST_PAY_ADS_MD5_IOS 					 "61026a43b78f7430950e15c4fe1e0cf5"
#define FIRST_PAY_ADS_MD5_SD 					 "e956a6fce03cdf0a8025d360d12fbcdd"


#define KEY_CROSS_PROMOTION 					 "cross_promotion"
#define KEY_CROSS_PROMOTION_ANDROID 					 "cross_promotion_android"
#define KEY_CROSS_PROMOTION_IOS 					 "cross_promotion_ios"
#define KEY_CROSS_PROMOTION_START_TIME 					 "cross_promotion_start_time"
#define KEY_CROSS_PROMOTION_END_TIME 					 "cross_promotion_end_time"
#define KEY_CROSS_PROMOTION_AVAILABLE 					 "cross_promotion_available"
#define KEY_CROSS_PROMOTION_IMAGE 					 "cross_promotion_img"
#define KEY_CROSS_PROMOTION_IMAGE_MD5 					 "cross_promotion_img_md5"
#define KEY_CROSS_PROMOTION_GIFT 					 "cross_promotion_gift"
#define KEY_CROSS_PROMOTION_TARGET_LINK 					 "cross_promotion_target_link"
#define KEY_CROSS_PROMOTION_PACKAGE_NAME 					 "cross_promotion_package_name"
#define KEY_CROSS_PROMOTION_APP_INFO 					 "cross_promotion_app_info"


#define KEY_ZALO_PAYMENT_APP_TIME 					 "app_time"
#define KEY_ZALO_PAYMENT_APP_TRANSACTION_ID 					 "app_transaction_id"
#define KEY_ZALO_PAYMENT_AMOUNT 					 "amount"
#define KEY_ZALO_PAYMENT_DESCRIPTION 					 "description"
#define KEY_ZALO_PAYMENT_EMBED_DATA 					 "embed_data"
#define KEY_ZALO_PAYMENT_MAC 					 "mac"

#define NEWSBOARD_SLOT_CHAR 					 "~"
#define NEWSBOARD_ITEMS_LIST_PATH 					 "./..log/newsboard_items_list.log"

#define KEY_CDN 					 "key_cdn"
#define KEY_CDN_LINK 					 "key_cdn_link_%d"
#define KEY_CDN_SPRITE_ID 					 "key_cdn_sprite_id_%d"
#define KEY_CDN_NAME 					 "key_cdn_name_%d"
#define KEY_CDN_MD5 					 "key_cdn_md5_%d"
#define KEY_CDN_PLATFORM 					 "key_cdn_platform_%d"
#define KEY_CDN_RESOLUTION 					 "key_cdn_resolution_%d"
#define KEY_CDN_TYPE 					 "key_cdn_type_%d"
#define KEY_CDN_ID 					 "key_cdn_id_%d"
#define KEY_CDN_TEXT_ID 					 "key_cdn_text_id_%d"

#define KEY_SHOW_MACHINE_ALERT 					 "key_show_machine_alert"
#define KEY_NUM_FRIEND_ALERT 					 "key_num_friend_alert"
#define KEY_ALERT 					 "key_alert"

#define KEY_USER_RANK 					 "user_rank"
#define KEY_RANK_RESULT 					 "rank_result_%d"
#define KEY_RANKING_USER_RECORD 					 "ranking_user_record"
#define KEY_RANKING_DELTA 					 "ranking_user_delta"
#define KEY_USER_RANKING_TARGET 					 "user_ranking_target"
#define KEY_RANKING_COUNT 					 "ranking_count"
#define KEY_RANKING_LAST_UDPATE 					 "ranking_last_update"
#define KEY_RANKING_INFO 					 "ranking_info"
#define KEY_RANKING_INFO_ACTIVE 					 "ranking_info_active"
#define KEY_RANKING_INFO_PREVIOUS 					 "ranking_info_previous"
#define KEY_RANKING_HARVEST 					 "ranking_harvest"
#define KEY_RANKING_SHOW_DETAISL_TIME 					 "ranking_show_details_time"
#define KEY_RANKING_START_TIME 					 "ranking_start_time"
#define KEY_RANKING_START_TIME_STR 					 "ranking_start_time_str"
#define KEY_RANKING_END_TIME 					 "ranking_end_time"
#define KEY_RANKING_END_TIME_STR 					 "ranking_end_time_str"
#define KEY_RANKING_DESCRIPTION 					 "ranking_description"
#define KEY_RANKING_CATEGORY 					 "ranking_ranking_category"
#define KEY_RANKING_TEXT_TEMPLATE 					 "ranking_text_template"
#define KEY_RANKING_TARGET 					 "ranking_target"
#define KEY_RANKING_UNIT 					 "ranking_unit"
#define KEY_RANKING_GIFT_1 					 "ranking_gift_rank_1"
#define KEY_RANKING_GIFT_2 					 "ranking_gift_rank_2"
#define KEY_RANKING_GIFT_3 					 "ranking_gift_rank_3"
#define KEY_RANKING_GIFT_100 					 "ranking_gift_rank_100"
#define KEY_RANKING_GIFT_BASIC 					 "ranking_gift_rank_basic"
#define KEY_RANKING_SIZE 					 "ranking_size"
#define KEY_RANKING_ACCUMULATION 					 "ranking_current_accumulation"
#define KEY_RANKING_FINAL_RESULT 					 "ranking_final_result"
#define KEY_RANKING_GIFT_RECEIVED 					 "ranking_gift_received"
#define KEY_RANKING_RECEIVED_BASIC_GIFT 					 "ranking_received_basic_gift"
#define KEY_RANKING_CLIENT_REFRESH 					 "ranking_client_refresh_time"
#define KEY_RANKING_IMG 					 "ranking_img"
#define KEY_RANKING_IMG_MD5 					 "ranking_img_md5"
#define KEY_RANKING_DETAILS 					 "ranking_details"
#define KEY_RANKING_DETAILS_MD5 					 "ranking_details_md5"
#define KEY_RANKING_TEMP_TEXT_1 					 "ranking_tmp_text_1"


#define KEY_ROTA_FORTUNAE_ID 					 "rota_fortunae_id"
#define KEY_ROTA_FORTUNAE_IS_PAID 					 "rota_fortunae_is_paid"
#define KEY_ROTA_FORTUNAE_DIAMOND_PRICE 					 "rota_fortunae_price"
#define KEY_ROTA_FORTUNAE_GIFT_REAL 					 "rota_fortunae_gift_real"
#define KEY_ROTA_FORTUNAE_GIFT_FAKE 					 "rota_fortunae_gift_fake"
#define KEY_ROTA_FORTUNAE_IS_USED 					 "rota_fortunae_is_used"
#define KEY_ROTA_FORTUNAE_TOTAL 					 "rota_fortunae_total"
#define KEY_ROTA_FORTUNAE_TOTAL_RETRY 					 "rota_fortunae_total_retry"
#define KEY_ROTA_FORTUNAE_START_TIME 					 "rota_fortunae_start_time"
#define KEY_ROTA_FORTUNAE_END_TIME 					 "rota_fortunae_end_time"
#define KEY_ROTA_FORTUNAE_GOLD_LIST 					 "rota_fortunae_gold_list"
#define KEY_ROTA_FORTUNAE_TOTAL_STAR 					 "rota_fortunae_total_star"
#define KEY_ROTA_FORTUNAE_IS_BOUGHT 					 "rota_fortunae_is_bought"
#define KEY_ROTA_FORTUNAE_IS_SALE_OFF 					 "rota_fortunae_is_sale_off"
#define KEY_ROTA_FORTUNAE_DIAMOND_SALE_OFF 					 "rota_fortunae_price_sale_off"

#define KEY_ROTA_FORTUNAE_INDEX 					 "rota_fortunae_%d"


#define KEY_EVENT_INFO 					 "event_info"
#define KEY_EVENT_MID_AUTUMN_FESTIVAL 					 "event_mid_autumn_festival"
#define KEY_EVENT_EXPORT 					 "event_export"
#define KEY_EVENT_HALLOWEEN 					 "event_halloween"
#define KEY_EVENT_20_11 					 "event_20_11"
#define KEY_EVENT_UPGRADE_POT 					 "event_upgrade_pot"
#define KEY_EVENT_XMAS_2014 					 "event_xmas_2014"
#define KEY_EVENT_XMAS_TREE_2014 					 "event_xmas_tree_2014"
#define KEY_EVENT_XMAS_MINI 					 "event_xmas_mini"
#define KEY_EVENT_NEW_YEAR_2015 					 "event_new_year_2015"
#define KEY_EVENT_ORDER_JAN_2015 					 "event_order_jan_2015"


#define KEY_MAIL_BOX 					 "mailbox"
#define KEY_MAIL 					 "mail"
#define KEY_MAIL_NUM 					 "mail_num"
#define KEY_MAIL_DATE 					 "mail_date"
#define KEY_MAIL_SENDER 					 "mail_sender"
#define KEY_MAIL_TITLE 					 "mail_title"
#define KEY_MAIL_CONTENT 					 "mail_content"
#define KEY_MAIL_GIFT_LIST 					 "mail_gift"
#define KEY_MAIL_READ 					 "mail_read"
#define KEY_MAIL_INDEX 					 "mail_index"
#define KEY_NEW_MAIL 					 "mail_new"


#define KEY_CHAT_SESSION 					 "chat_session"
#define KEY_CHAT_MESSAGE 					 "chat_message"
#define KEY_LAST_MESSAGE_IDX 					 "last_message_idx"
#define KEY_MESSAGE_NUM 					 "message_num"
#define KEY_SENDER_ID 					 "sender_id"
#define KEY_SENDER_NAME 					 "sender_name"
#define KEY_MESSAGE_TYPE 					 "message_type"
#define KEY_MESSAGE_CONTENT 					 "message_content"
#define KEY_ROOM_ID 					 "room_id"
#define KEY_MESSAGE_PACK 					 "message_pack_%d"
#define KEY_ROOM_CAPACITY_MAX 					 "room_capacity_max"
#define KEY_ROOM_REFRESH_DURATION 					 "room_refresh_duration"
#define KEY_ROOM_MESSAGE_LENGTH 					 "room_message_length"
#define KEY_ROOM_MESSAGE_DELAY 					 "room_message_delay"
#define KEY_ROOM_WELCOME 					 "room_welcome_message"
#define KEY_ROOM_OWNER 					 "room_owner"
#define KEY_CHAT_ENABLE 					 "chat_enable"
#define KEY_CHAT_ADDRESS 					 "chat_address"
#define KEY_CHAT_PORT 					 "chat_port"


#define KEY_RECEIPT_DATA 					 "receipt_data"
#define KEY_RECEIPT_PASSWORD 					 "receipt_password"
#define KEY_APPLE_IAB_PRODUCT_ID 					 "apple_IAB_product_id"


#define KEY_ANDROID_DEVELOPER_PAYLOAD 					 "android_developer_payload"
#define KEY_ANDROID_IAB_RESPONSE_CODE 					 "android_IAB_response_code"
#define KEY_ANDROID_IAB_PURCHASE_DATA 					 "android_IAP_purchase_data"
#define KEY_ANDROID_IAP_DATA_SIGNATURE 					 "andorid_IAP_data_signature"
#define KEY_ANDROID_IAB_PRODUCT_ID 					 "android_IAB_product_id"


#define KEY_WIN_PRODUCT_ID 					 "win_IAB_product_id"


#define KEY_ITEM_EVENT_DROP_FEATURE_DAILY_ORDER 					 "event_drop_num_feature_daily_order"
#define KEY_ITEM_EVENT_DROP_FEATURE_ORDER_NORMAL 					 "event_drop_num_feature_normal"
#define KEY_ITEM_EVENT_DROP_FEATURE_ORDER_EVENT 					 "event_drop_num_feature_order_event"
#define KEY_ITEM_EVENT_DROP_FEATURE_AIRSHIP 					 "event_drop_num_feature_airship"
#define KEY_ITEM_EVENT_DROP_FEATURE_TOM 					 "event_drop_num_feature_tom"
#define KEY_ITEM_EVENT_DROP_FEATURE_FORTUNE 					 "event_drop_num_feature_fortune"
#define KEY_ITEM_EVENT_DROP_FEATURE_MERCHANTE 					 "event_drop_num_feature_merchant"
#define KEY_STOCK_EVENT 					 "stock_event"


#define KEY_USE_NPC_CUSTOME 					 "use_npc_custome"
#define KEY_SNOW 					 "use_snow"


#define APPFLYER_MEDIA_SOURCE_KEY 					 "media_source"
#define APPFLYER_CAMPAIGN_NAME_KEY 					 "campaign_name"
#define APPFLYER_COMPAIGN_ID_KEY 					 "campaign_id"
#define APPFLYER_IS_FB_KEY 					 "is_fb"
#define APPFLYER_ADGROUP_NAME_KEY 					 "adgroup_name"
#define APPFLYER_ADGROUP_ID_KEY 					 "adgroup_id"
#define APPFLYER_ADSET_NAME_KEY 					 "adset_name"
#define APPFLYER_ADSET_ID_KEY 					 "adset_id"
#define APPFLYER_AD_ID_KEY 					 "ad_id"
#define APPFLYER_AF_SITEID_KEY 					 "af_siteid"
#define APPFLYER_AF_SUB1_KEY 					 "af_sub1"
#define APPFLYER_AF_SUB2_KEY 					 "af_sub2"
#define APPFLYER_AF_SUB3_KEY 					 "af_sub3"
#define APPFLYER_AF_SUB4_KEY 					 "af_sub4"
#define APPFLYER_AF_SUB5_KEY 					 "af_sub5"
#define APPFLYER_INSTALL_TIME_KEY 					 "install_time"
#define APPFLYER_ID 					 "af_id"
#define PIG_ID 					 "pig_id"
#define DEVICE_OS 					 "device_os"


#define KEY_FORWARD_SERVER_IP 					 "forward_server_ip"
#define KEY_FORWARD_SERVER_PORT 					 "forward_server_port"


#define KEY_OFFER_BUG 					 "offer_bug"
#define KEY_OFFER_GEM 					 "offer_gem"
#define KEY_OFFER_FLOOR 					 "offer_floor"
#define KEY_OFFER_MACHINE 					 "offer_machine"
#define KEY_OFFER_LUCKY_LEAF_GREEN 					 "offer_lucky_leaf"
#define KEY_OFFER_LUCKY_LEAF_PURPLE 					 "offer_lucky_leaf_purple"
#define KEY_OFFER_GOLD 					 "offer_gold"


#define KEY_BONUS_PLANT 					 "bonus_plant"
#define KEY_BONUS_AIRSHIP_GOLD 					 "bonus_airship_gold"
#define KEY_BONUS_AIRSHIP_EXP 					 "bonus_airship_exp"
#define KEY_BONUS_ORDER_NORMAL 					 "bonus_order_normal"
#define KEY_BONUS_ORDER_DAILY 					 "bonus_order_daily"

#define KEY_NUM_GIFT_FROM_FRIEND 					 "num_gift_from_friend"

#define KEY_RESPONSE_STRING 					 "resonse_string"

